// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // App_ApplicationInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AppApplicationInfo : Entity<Guid>
    {
        public string AppId { get; set; } // AppID (Primary key) (length: 10)
        public string AppName { get; set; } // AppName (length: 50)
        public string AppPwd { get; set; } // AppPwd (length: 100)
        public string AppLocation { get; set; } // AppLocation (length: 100)
        public string AppServiceHost { get; set; } // AppServiceHost (length: 255)
        public string AppPortalUrl { get; set; } // AppPortalUrl (length: 1000)
        public string AppAdminUrl { get; set; } // AppAdminURL (length: 1000)
        public string AppPortalName { get; set; } // AppPortalName (length: 20)
        public string AppAdminName { get; set; } // AppAdminName (length: 20)
        public int? AppStatus { get; set; } // AppStatus
        public int? OrderNum { get; set; } // OrderNum
        public string AppInternalServiceHost { get; set; } // AppInternalServiceHost (length: 255)
        public string LanguageCode { get; set; } // LanguageCode (length: 20)
        public string DebugServiceHost { get; set; } // DebugServiceHost (length: 255)
        public string FunctionAppId { get; set; } // FunctionAppID (length: 10)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
