// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // App_ServiceInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AppServiceInfo : Entity<Guid>
    {
        public string ServiceId { get; set; } // ServiceID (Primary key) (length: 50)
        public string AppId { get; set; } // AppID (length: 10)
        public string ServiceCode { get; set; } // ServiceCode (length: 50)
        public string ServiceUrl { get; set; } // ServiceURL (length: 1000)
        public string FunctionName { get; set; } // FunctionName (length: 100)
        public string ServiceType { get; set; } // ServiceType (length: 1)
        public string ServiceName { get; set; } // ServiceName (length: 100)
        public string NewVersionId { get; set; } // NewVersionID (length: 50)
        public string Description { get; set; } // Description (length: 1000)
        public string Explain { get; set; } // Explain (length: 1073741823)
        public int? Status { get; set; } // Status
        public int? CacheMinutes { get; set; } // CacheMinutes
        public string ClassName { get; set; } // ClassName (length: 100)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child AppServiceParameters where [App_ServiceParameter].[ServiceID] point to this entity (RefApp_ServiceInfo26)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AppServiceParameter> AppServiceParameters { get; set; } // App_ServiceParameter.RefApp_ServiceInfo26

        public AppServiceInfo()
        {
            AppServiceParameters = new System.Collections.Generic.List<AppServiceParameter>();
        }
    }

}
// </auto-generated>
