// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // App_ServiceParameter
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AppServiceParameter : Entity<Guid>
    {
        public string ParamId { get; set; } // ParamID (Primary key) (length: 50)
        public string ServiceId { get; set; } // ServiceID (length: 50)
        public string ParameterName { get; set; } // ParameterName (length: 50)
        public int? OrderNum { get; set; } // OrderNum
        public string DataType { get; set; } // DataType (length: 100)
        public string DefaultValue { get; set; } // DefaultValue (length: 1000)
        public string Description { get; set; } // Description (length: 1000)
        public int? Status { get; set; } // Status

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent AppServiceInfo pointed by [App_ServiceParameter].([ServiceId]) (RefApp_ServiceInfo26)
        /// </summary>
        public virtual AppServiceInfo AppServiceInfo { get; set; } // RefApp_ServiceInfo26
    }

}
// </auto-generated>
