// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table '2017虹桥太平桥预算数导入OEMS' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // 2017虹桥太平桥预算数导入OEMS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class C2017虹桥太平桥预算数导入oems : Entity<Guid>
    {
        public double? SunYear { get; set; } // sunYear
        public string SunDb { get; set; } // SUN_DB (length: 255)
        public double? AccountCode { get; set; } // AccountCode
        public string T8Code { get; set; } // T8_Code (length: 255)
        public string T4Code { get; set; } // T4_Code (length: 255)
        public string T7Code { get; set; } // T7_Code (length: 255)
        public string 组织机构 { get; set; } // 组织机构 (length: 255)
        public string Entity { get; set; } // Entity (length: 255)
        public double? YearTotal { get; set; } // YearTotal
        public double? Month1 { get; set; } // Month1
        public double? Month2 { get; set; } // Month2
        public double? Month3 { get; set; } // Month3
        public double? Month4 { get; set; } // Month4
        public double? Month5 { get; set; } // Month5
        public double? Month6 { get; set; } // Month6
        public double? Month7 { get; set; } // Month7
        public double? Month8 { get; set; } // Month8
        public double? Month9 { get; set; } // Month9
        public double? Month10 { get; set; } // Month10
        public double? Month11 { get; set; } // Month11
        public double? Month12 { get; set; } // Month12

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
