// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'CAPEX18年预算' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // CAPEX18年预算
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Capex18年预算 : Entity<Guid>
    {
        public string Entity { get; set; } // Entity (length: 255)
        public string T4 { get; set; } // T4 (length: 255)
        public string T8 { get; set; } // T8 (length: 255)
        public string 地块 { get; set; } // 地块 (length: 255)
        public string T7 { get; set; } // T7 (length: 255)
        public double? C1月 { get; set; } // 1月
        public double? C2月 { get; set; } // 2月
        public double? C3月 { get; set; } // 3月
        public double? C4月 { get; set; } // 4月
        public double? C5月 { get; set; } // 5月
        public double? C6月 { get; set; } // 6月
        public double? C7月 { get; set; } // 7月
        public double? C8月 { get; set; } // 8月
        public double? C9月 { get; set; } // 9月
        public double? C10月 { get; set; } // 10月
        public double? C11月 { get; set; } // 11月
        public double? C12月 { get; set; } // 12月

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
