// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'CAPEX18年预算2' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // CAPEX18年预算2
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Capex18年预算2 : Entity<Guid>
    {
        public string T4 { get; set; } // T4 (length: 255)
        public string T7 { get; set; } // T7 (length: 255)
        public string T8 { get; set; } // T8 (length: 255)
        public double? Month1 { get; set; } // Month1
        public double? Month2 { get; set; } // Month2
        public double? Month3 { get; set; } // Month3
        public double? Month4 { get; set; } // Month4
        public double? Month5 { get; set; } // Month5
        public double? Month6 { get; set; } // Month6
        public double? Month7 { get; set; } // Month7
        public double? Month8 { get; set; } // Month8
        public double? Month9 { get; set; } // Month9
        public double? Month10 { get; set; } // Month10
        public double? Month11 { get; set; } // Month11
        public double? Month12 { get; set; } // Month12
        public double? F16 { get; set; } // F16

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
