// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // Log_LoginLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class LogLoginLog : Entity<Guid>
    {
        public int LoginLogId { get; set; } // LoginLogID (Primary key)
        public string AppId { get; set; } // AppID (length: 10)
        public string Token { get; set; } // Token (length: 100)
        public string UserId { get; set; } // UserID (length: 50)
        public string UserName { get; set; } // UserName (length: 50)
        public string InputPassword { get; set; } // InputPassword (length: 100)
        public int? Result { get; set; } // Result
        public string LoginIp { get; set; } // LoginIP (length: 50)
        public System.DateTime? LoginTime { get; set; } // LoginTime
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string F4 { get; set; } // F4 (length: 1000)
        public string F5 { get; set; } // F5 (length: 1000)
        public string F6 { get; set; } // F6 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
