// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // Log_UseroperationLog_OEMS
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class LogUseroperationLogOem : Entity<Guid>
    {
        public string UserOperationLogId { get; set; } // UserOperationLogID (Primary key) (length: 50)
        public string AppId { get; set; } // AppID (length: 10)
        public string Token { get; set; } // Token (length: 100)
        public string UserId { get; set; } // UserID (length: 50)
        public string UserName { get; set; } // UserName (length: 20)
        public string TheKey { get; set; } // TheKey (length: 50)
        public string Category { get; set; } // Category (length: 20)
        public string ActionType { get; set; } // ActionType (length: 20)
        public string ActionDescription { get; set; } // ActionDescription (length: 200)
        public string ActionResult { get; set; } // ActionResult (length: 10)
        public System.DateTime? LogTime { get; set; } // LogTime
        public string IpAddress { get; set; } // IPAddress (length: 50)
        public string ErrorCode { get; set; } // ErrorCode (length: 100)
        public string ExceptionMsg { get; set; } // ExceptionMsg (length: 100)
        public string DataXml { get; set; } // DataXML (length: 1073741823)
        public string ModuleId { get; set; } // ModuleID (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string F4 { get; set; } // F4 (length: 1000)
        public string F5 { get; set; } // F5 (length: 1000)
        public string F6 { get; set; } // F6 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
