// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // MDM_Supplier
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class MdmSupplier : Entity<Guid>
    {
        public string SupplierGuid { get; set; } // SupplierGUID (Primary key) (length: 50)
        public string SupplierCode { get; set; } // SupplierCode (length: 50)
        public string FullName { get; set; } // FullName (length: 50)
        public string Abbreviation { get; set; } // Abbreviation (length: 10)
        public string Address { get; set; } // Address (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public string RelateCompany { get; set; } // RelateCompany (length: 50)
        public string SupplierType { get; set; } // SupplierType (length: 50)
        public string ProfessionType { get; set; } // ProfessionType (length: 50)
        public string Scope { get; set; } // Scope (length: 50)
        public string SupplierDegree { get; set; } // SupplierDegree (length: 50)
        public decimal? BusinessSize { get; set; } // BusinessSize
        public int? MemberNumber { get; set; } // MemberNumber
        public string CorporateRepresentative { get; set; } // CorporateRepresentative (length: 200)
        public string BusinessNature { get; set; } // BusinessNature (length: 50)
        public string InstitutionCode { get; set; } // InstitutionCode (length: 50)
        public string BusinessVolume { get; set; } // BusinessVolume (length: 50)
        public string TaxCode { get; set; } // TaxCode (length: 50)
        public string RegisterAddress { get; set; } // RegisterAddress (length: 200)
        public decimal? RegisterCapital { get; set; } // RegisterCapital
        public string QualifiedDegree { get; set; } // QualifiedDegree (length: 50)
        public string ProductService { get; set; } // ProductService (length: 500)
        public string Country { get; set; } // Country (length: 50)
        public string Province { get; set; } // Province (length: 50)
        public string City { get; set; } // City (length: 50)
        public string ZipCode { get; set; } // ZipCode (length: 50)
        public string Telephone { get; set; } // Telephone (length: 50)
        public string Fax { get; set; } // Fax (length: 50)
        public string BankName { get; set; } // BankName (length: 50)
        public string BankAddress { get; set; } // BankAddress (length: 200)
        public string BankAccount { get; set; } // BankAccount (length: 50)
        public int? Status { get; set; } // Status
        public string Remark { get; set; } // Remark (length: 200)
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public string ModifyUser { get; set; } // ModifyUser (length: 50)
        public System.DateTime? ModifyDate { get; set; } // ModifyDate
        public string F1 { get; set; } // F1 (length: 200)
        public string F2 { get; set; } // F2 (length: 200)
        public string F3 { get; set; } // F3 (length: 200)
        public string F4 { get; set; } // F4 (length: 200)
        public string F5 { get; set; } // F5 (length: 200)
        public string F6 { get; set; } // F6 (length: 200)
        public int? IsSystem { get; set; } // IsSystem

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
