// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // MDM_Supplier_Contacts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class MdmSupplierContact : Entity<Guid>
    {
        public string SupplierContactsGuid { get; set; } // SupplierContactsGUID (Primary key) (length: 50)
        public string Name { get; set; } // Name (length: 50)
        public int ContactsType { get; set; } // ContactsType
        public string PaperType { get; set; } // PaperType (length: 50)
        public string PaperNumber { get; set; } // PaperNumber (length: 50)
        public string MobilePhone { get; set; } // MobilePhone (length: 50)
        public string Email { get; set; } // Email (length: 50)
        public string BusinessAddress { get; set; } // BusinessAddress (length: 50)
        public string BusinessTelephone { get; set; } // BusinessTelephone (length: 50)
        public int? Status { get; set; } // Status
        public string Remark { get; set; } // Remark (length: 200)
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public string ModifyUser { get; set; } // ModifyUser (length: 50)
        public System.DateTime? ModifyDate { get; set; } // ModifyDate
        public string F1 { get; set; } // F1 (length: 200)
        public string F2 { get; set; } // F2 (length: 200)
        public string F3 { get; set; } // F3 (length: 200)
        public string F4 { get; set; } // F4 (length: 200)
        public string F5 { get; set; } // F5 (length: 200)
        public string F6 { get; set; } // F6 (length: 200)
        public string SupplierGuid { get; set; } // SupplierGUID (length: 50)
        public int? IsSystem { get; set; } // IsSystem

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
