// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'OEMS_T4_Description_Mapping' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // OEMS_T4_Description_Mapping
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class OemsT4DescriptionMapping : Entity<Guid>
    {
        public string Objectcode { get; set; } // objectcode (length: 255)
        public string ObjectName { get; set; } // ObjectName (length: 255)
        public string DepartmentCode { get; set; } // DepartmentCode (length: 255)
        public string SCode { get; set; } // SCode (length: 255)
        public string AliasValue { get; set; } // AliasValue (length: 255)
        public string Id { get; set; } // id (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
