// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'Sheet1$' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // Sheet1$
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class Sheet136 : Entity<Guid>
    {
        public string 服务单编号 { get; set; } // 服务单编号 (length: 255)
        public string 服务单名称 { get; set; } // 服务单名称 (length: 255)
        public string 经办人 { get; set; } // 经办人 (length: 255)
        public string 部门 { get; set; } // 部门 (length: 255)
        public string 地块 { get; set; } // 地块 (length: 255)
        public string 账单公司 { get; set; } // 账单公司 (length: 255)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
