// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'SUN_BUDGETDATA' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // SUN_BUDGETDATA
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SunBudgetdata : Entity<Guid>
    {
        public int? SunYear { get; set; } // sunYear
        public int? Period { get; set; } // Period
        public string SunDb { get; set; } // SUN_DB (length: 3)
        public string DbType { get; set; } // DB_TYPE (length: 3)
        public string AccountCode { get; set; } // AccountCode (length: 15)
        public string AccountDesc { get; set; } // AccountDesc (length: 50)
        public string JrnalSrce { get; set; } // JRNAL_SRCE (length: 5)
        public string T0Code { get; set; } // T0_Code (length: 15)
        public string T1Code { get; set; } // T1_Code (length: 15)
        public string T2Code { get; set; } // T2_Code (length: 15)
        public string T3Code { get; set; } // T3_Code (length: 15)
        public string T4Code { get; set; } // T4_Code (length: 15)
        public string T5Code { get; set; } // T5_Code (length: 15)
        public string T6Code { get; set; } // T6_Code (length: 15)
        public string T7Code { get; set; } // T7_Code (length: 15)
        public string T8Code { get; set; } // T8_Code (length: 15)
        public decimal? OpenBalance { get; set; } // OpenBalance
        public decimal? DebitAmount { get; set; } // DebitAmount
        public decimal? CreditAmount { get; set; } // CreditAmount
        public decimal? EndBalance { get; set; } // EndBalance

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
