// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // SYS_DataRights
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SysDataRight : Entity<Guid>
    {
        public string DataRightsId { get; set; } // DataRightsID (Primary key) (length: 50)
        public int? RoleId { get; set; } // RoleID
        public string ModuleId { get; set; } // ModuleID (length: 50)
        public string DataRightsType { get; set; } // DataRightsType (length: 10)
        public string ProjectId { get; set; } // ProjectID (length: 2147483647)
        public string CostCenterId { get; set; } // CostCenterId (length: 2147483647)
        public string BlockId { get; set; } // BlockId (length: 2147483647)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent SysModule pointed by [SYS_DataRights].([ModuleId]) (RefSYS_Module345)
        /// </summary>
        public virtual SysModule SysModule { get; set; } // RefSYS_Module345

        /// <summary>
        /// Parent SysRole pointed by [SYS_DataRights].([RoleId]) (RefSYS_Role343)
        /// </summary>
        public virtual SysRole SysRole { get; set; } // RefSYS_Role343
    }

}
// </auto-generated>
