// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // SYS_ModuleDetailInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SysModuleDetailInfo : Entity<Guid>
    {
        public string ModuleDetailId { get; set; } // ModuleDetailID (Primary key) (length: 50)
        public string ModuleId { get; set; } // ModuleID (length: 50)
        public string FunctionUrl { get; set; } // FunctionURL (length: 100)
        public string ModuleName { get; set; } // ModuleName (length: 20)
        public string LanguageCode { get; set; } // LanguageCode (length: 10)
        public string F1 { get; set; } // F1 (length: 2000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent SysModule pointed by [SYS_ModuleDetailInfo].([ModuleId]) (RefSYS_Module6)
        /// </summary>
        public virtual SysModule SysModule { get; set; } // RefSYS_Module6
    }

}
// </auto-generated>
