// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // SYS_Module
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SysModule : Entity<Guid>
    {
        public string ModuleId { get; set; } // ModuleID (Primary key) (length: 50)
        public string ParentModuleId { get; set; } // ParentModuleID (length: 50)
        public string PageType { get; set; } // PageType (length: 1)
        public string Modulerights { get; set; } // MODULERIGHTS (length: 100)
        public string AppId { get; set; } // AppId (length: 50)
        public int? OrderNo { get; set; } // OrderNo
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child SysDataRights where [SYS_DataRights].[ModuleID] point to this entity (RefSYS_Module345)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysDataRight> SysDataRights { get; set; } // SYS_DataRights.RefSYS_Module345
        /// <summary>
        /// Child SysModuleDetailInfoes where [SYS_ModuleDetailInfo].[ModuleID] point to this entity (RefSYS_Module6)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysModuleDetailInfo> SysModuleDetailInfoes { get; set; } // SYS_ModuleDetailInfo.RefSYS_Module6
        /// <summary>
        /// Child SysRoleRights where [SYS_RoleRights].[ModuleID] point to this entity (RefSYS_Module8)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysRoleRight> SysRoleRights { get; set; } // SYS_RoleRights.RefSYS_Module8

        public SysModule()
        {
            SysDataRights = new System.Collections.Generic.List<SysDataRight>();
            SysModuleDetailInfoes = new System.Collections.Generic.List<SysModuleDetailInfo>();
            SysRoleRights = new System.Collections.Generic.List<SysRoleRight>();
        }
    }

}
// </auto-generated>
