// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // SYS_Parameter
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SysParameter : Entity<Guid>
    {
        public string ParameterId { get; set; } // ParameterID (Primary key) (length: 50)
        public string Code { get; set; } // Code (length: 20)
        public string Name { get; set; } // Name (length: 20)
        public string Value { get; set; } // Value (length: 20)
        public int? OrderNum { get; set; } // OrderNum
        public int? Status { get; set; } // Status
        public string Remark { get; set; } // Remark (length: 1073741823)
        public string UpperId { get; set; } // UpperID (length: 50)
        public string TypeCode { get; set; } // TypeCode (length: 20)
        public string TypeName { get; set; } // TypeName (length: 20)
        public string CreateUserId { get; set; } // CreateUserID (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string ModifyUserId { get; set; } // ModifyUserID (length: 50)
        public System.DateTime? ModifyDate { get; set; } // ModifyDate

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
