// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // SYS_RoleRights
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SysRoleRight : Entity<Guid>
    {
        public string RoleRightsId { get; set; } // RoleRightsID (Primary key) (length: 50)
        public string DataRights { get; set; } // DataRights (length: 50)
        public string RightsCode { get; set; } // RightsCode (length: 10)
        public string ModuleId { get; set; } // ModuleID (length: 50)
        public int RoleId { get; set; } // RoleID

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent SysModule pointed by [SYS_RoleRights].([ModuleId]) (RefSYS_Module8)
        /// </summary>
        public virtual SysModule SysModule { get; set; } // RefSYS_Module8

        /// <summary>
        /// Parent SysRole pointed by [SYS_RoleRights].([RoleId]) (RefSYS_Role9)
        /// </summary>
        public virtual SysRole SysRole { get; set; } // RefSYS_Role9
    }

}
// </auto-generated>
