// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // SYS_Role
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SysRole : Entity<Guid>
    {
        public int RoleId { get; set; } // RoleID (Primary key)
        public string RoleType { get; set; } // RoleType (length: 1)
        public string RoleName { get; set; } // RoleName (length: 20)
        public string Description { get; set; } // Description (length: 200)
        public string Status { get; set; } // Status (length: 1)
        public string CreateUserId { get; set; } // CreateUserID (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string ModifyUserId { get; set; } // ModifyUserID (length: 50)
        public System.DateTime? ModifyDate { get; set; } // ModifyDate
        public int? IsDistrictFinance { get; set; } // IsDistrictFinance
        public int? ModifyPaymentSignEnable { get; set; } // ModifyPaymentSignEnable
        public int? PayEnable { get; set; } // PayEnable
        public string BudgetTypeIDs { get; set; } // BudgetTypeIDs (length: 8000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child SysDataRights where [SYS_DataRights].[RoleID] point to this entity (RefSYS_Role343)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysDataRight> SysDataRights { get; set; } // SYS_DataRights.RefSYS_Role343
        /// <summary>
        /// Child SysRoleRights where [SYS_RoleRights].[RoleID] point to this entity (RefSYS_Role9)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysRoleRight> SysRoleRights { get; set; } // SYS_RoleRights.RefSYS_Role9
        /// <summary>
        /// Child SysUserRoles where [SYS_UserRole].[RoleID] point to this entity (RefSYS_Role7)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysUserRole> SysUserRoles { get; set; } // SYS_UserRole.RefSYS_Role7

        public SysRole()
        {
            SysDataRights = new System.Collections.Generic.List<SysDataRight>();
            SysRoleRights = new System.Collections.Generic.List<SysRoleRight>();
            SysUserRoles = new System.Collections.Generic.List<SysUserRole>();
        }
    }

}
// </auto-generated>
