// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // SYS_UserRole
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class SysUserRole : Entity<Guid>
    {
        public int UserRoleId { get; set; } // UserRoleID (Primary key)
        public int RoleId { get; set; } // RoleID
        public string UserId { get; set; } // UserID (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent SysRole pointed by [SYS_UserRole].([RoleId]) (RefSYS_Role7)
        /// </summary>
        public virtual SysRole SysRole { get; set; } // RefSYS_Role7

        /// <summary>
        /// Parent TbUser pointed by [SYS_UserRole].([UserId]) (RefTB_User10)
        /// </summary>
        public virtual TbUser TbUser { get; set; } // RefTB_User10
    }

}
// </auto-generated>
