// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Accounting_Items_bak
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbAccountingItemsBak : Entity<Guid>
    {
        public string AccountingItemId { get; set; } // AccountingItemID (Primary key) (length: 50)
        public string ItemCode { get; set; } // ItemCode (Primary key) (length: 20)
        public string ItemName { get; set; } // ItemName (Primary key) (length: 50)
        public string AccountingItemDesc { get; set; } // AccountingItemDesc (length: 1000)
        public int? IsInvalid { get; set; } // IsInvalid
        public System.DateTime? AvailabilityDate { get; set; } // AvailabilityDate
        public System.DateTime? ExpiryDate { get; set; } // ExpiryDate
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string UpperId { get; set; } // UpperID (length: 50)
        public int? OrderIndex { get; set; } // OrderIndex
        public string ManageType { get; set; } // ManageType (length: 10)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
