// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Budget_Plan_Budget_Item
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetPlanBudgetItem : Entity<Guid>
    {
        public string BudgetItemId { get; set; } // BudgetItemID (Primary key) (length: 50)
        public string UpperBudgetItemId { get; set; } // UpperBudgetItemID (length: 50)
        public string BudgetItemCode { get; set; } // BudgetItemCode (length: 20)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string BpCostCenterId { get; set; } // BP_CostCenterID (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbBudgetPlanCostCenter pointed by [TB_Budget_Plan_Budget_Item].([BpCostCenterId]) (RefTB_Budget_Plan_CostCenter117)
        /// </summary>
        public virtual TbBudgetPlanCostCenter TbBudgetPlanCostCenter { get; set; } // RefTB_Budget_Plan_CostCenter117
    }

}
// </auto-generated>
