// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Budget_Control
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetControl : Entity<Guid>
    {
        public string BudgetControlId { get; set; } // BudgetControlID (Primary key) (length: 50)
        public int Version { get; set; } // Version
        public string Creator { get; set; } // Creator (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string CreatorDept { get; set; } // CreatorDept (length: 50)
        public System.DateTime? CreatorDate { get; set; } // CreatorDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string UpdateUserName { get; set; } // UpdateUserName (length: 50)
        public string UpdateUserDept { get; set; } // UpdateUserDept (length: 50)
        public System.DateTime? UpdateUserDate { get; set; } // UpdateUserDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetControlDetails where [TB_Budget_Control_Detail].[BudgetControlID] point to this entity (RefTB_Budget_Control166)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetControlDetail> TbBudgetControlDetails { get; set; } // TB_Budget_Control_Detail.RefTB_Budget_Control166

        public TbBudgetControl()
        {
            TbBudgetControlDetails = new System.Collections.Generic.List<TbBudgetControlDetail>();
        }
    }

}
// </auto-generated>
