// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Budget_Plan_CostCenter_V1
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetPlanCostCenterV1 : Entity<Guid>
    {
        public string BpCostCenterId { get; set; } // BP_CostCenterID (Primary key) (length: 50)
        public string VersionId { get; set; } // VersionID (length: 50)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string CostCenterName { get; set; } // CostCenterName (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetPlanCostCenterYearDetailV1 where [TB_Budget_Plan_CostCenter_YearDetail_V1].[BP_CostCenterID] point to this entity (RefTB_Budget_Plan_CostCenter_V11071)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanCostCenterYearDetailV1> TbBudgetPlanCostCenterYearDetailV1 { get; set; } // TB_Budget_Plan_CostCenter_YearDetail_V1.RefTB_Budget_Plan_CostCenter_V11071

        // Foreign keys

        /// <summary>
        /// Parent TbBudgetPlanVersionV1 pointed by [TB_Budget_Plan_CostCenter_V1].([VersionId]) (RefTB_Budget_Plan_Version_V11061)
        /// </summary>
        public virtual TbBudgetPlanVersionV1 TbBudgetPlanVersionV1 { get; set; } // RefTB_Budget_Plan_Version_V11061

        /// <summary>
        /// Parent TbCostCenter pointed by [TB_Budget_Plan_CostCenter_V1].([CostCenterId]) (RefTB_CostCenter1131)
        /// </summary>
        public virtual TbCostCenter TbCostCenter { get; set; } // RefTB_CostCenter1131

        public TbBudgetPlanCostCenterV1()
        {
            TbBudgetPlanCostCenterYearDetailV1 = new System.Collections.Generic.List<TbBudgetPlanCostCenterYearDetailV1>();
        }
    }

}
// </auto-generated>
