// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Budget_Plan_Version_V1
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetPlanVersionV1 : Entity<Guid>
    {
        public string VersionId { get; set; } // VersionID (Primary key) (length: 50)
        public string VersionTypeId { get; set; } // VersionTypeID (length: 50)
        public string VersionTypeName { get; set; } // VersionTypeName (length: 50)
        public string YearId { get; set; } // YearID (length: 50)
        public int? Year { get; set; } // Year
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockName { get; set; } // BlockName (length: 50)
        public string BudgetTypeId { get; set; } // BudgetTypeID (length: 50)
        public string BudgetTypeName { get; set; } // BudgetTypeName (length: 50)
        public string VersionDesc { get; set; } // VersionDesc (length: 1000)
        public int? Status { get; set; } // Status
        public int? ProcInstId { get; set; } // ProcInstID
        public string LatestApprover { get; set; } // LatestApprover (length: 50)
        public string LatestComment { get; set; } // LatestComment (length: 1000)
        public System.DateTime? LatestApproveTime { get; set; } // LatestApproveTime
        public string Creator { get; set; } // Creator (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string UpdateUserName { get; set; } // UpdateUserName (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetPlanCostCenterV1 where [TB_Budget_Plan_CostCenter_V1].[VersionID] point to this entity (RefTB_Budget_Plan_Version_V11061)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanCostCenterV1> TbBudgetPlanCostCenterV1 { get; set; } // TB_Budget_Plan_CostCenter_V1.RefTB_Budget_Plan_Version_V11061

        // Foreign keys

        /// <summary>
        /// Parent TbBlock pointed by [TB_Budget_Plan_Version_V1].([BlockId]) (RefTB_Block334)
        /// </summary>
        public virtual TbBlock TbBlock { get; set; } // RefTB_Block334

        /// <summary>
        /// Parent TbBudgetType pointed by [TB_Budget_Plan_Version_V1].([BudgetTypeId]) (RefTB_BudgetType301)
        /// </summary>
        public virtual TbBudgetType TbBudgetType { get; set; } // RefTB_BudgetType301

        /// <summary>
        /// Parent TbBudgetVersionType pointed by [TB_Budget_Plan_Version_V1].([VersionTypeId]) (RefTB_BudgetVersionType297)
        /// </summary>
        public virtual TbBudgetVersionType TbBudgetVersionType { get; set; } // RefTB_BudgetVersionType297

        /// <summary>
        /// Parent TbYear pointed by [TB_Budget_Plan_Version_V1].([YearId]) (RefTB_Year299)
        /// </summary>
        public virtual TbYear TbYear { get; set; } // RefTB_Year299

        public TbBudgetPlanVersionV1()
        {
            TbBudgetPlanCostCenterV1 = new System.Collections.Generic.List<TbBudgetPlanCostCenterV1>();
        }
    }

}
// </auto-generated>
