// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Budget_Plan_Adjustment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetPlanAdjustment : Entity<Guid>
    {
        public string AdjustmentId { get; set; } // AdjustmentID (Primary key) (length: 50)
        public string VersionId { get; set; } // VersionID (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string BudgetItemCode { get; set; } // BudgetItemCode (length: 20)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 200)
        public decimal? BeforeAdjustmentAmount1 { get; set; } // BeforeAdjustmentAmount1
        public decimal? AfterAdjustmentAmount1 { get; set; } // AfterAdjustmentAmount1
        public decimal? BeforeAdjustmentAmount2 { get; set; } // BeforeAdjustmentAmount2
        public decimal? AfterAdjustmentAmount2 { get; set; } // AfterAdjustmentAmount2
        public decimal? BeforeAdjustmentAmount3 { get; set; } // BeforeAdjustmentAmount3
        public decimal? AfterAdjustmentAmount3 { get; set; } // AfterAdjustmentAmount3
        public decimal? BeforeAdjustmentAmount4 { get; set; } // BeforeAdjustmentAmount4
        public decimal? AfterAdjustmentAmount4 { get; set; } // AfterAdjustmentAmount4
        public decimal? BeforeAdjustmentAmount5 { get; set; } // BeforeAdjustmentAmount5
        public decimal? AfterAdjustmentAmount5 { get; set; } // AfterAdjustmentAmount5
        public decimal? BeforeAdjustmentAmount6 { get; set; } // BeforeAdjustmentAmount6
        public decimal? AfterAdjustmentAmount6 { get; set; } // AfterAdjustmentAmount6
        public decimal? BeforeAdjustmentAmount7 { get; set; } // BeforeAdjustmentAmount7
        public decimal? AfterAdjustmentAmount7 { get; set; } // AfterAdjustmentAmount7
        public decimal? BeforeAdjustmentAmount8 { get; set; } // BeforeAdjustmentAmount8
        public decimal? AfterAdjustmentAmount8 { get; set; } // AfterAdjustmentAmount8
        public decimal? BeforeAdjustmentAmount9 { get; set; } // BeforeAdjustmentAmount9
        public decimal? AfterAdjustmentAmount9 { get; set; } // AfterAdjustmentAmount9
        public decimal? BeforeAdjustmentAmount10 { get; set; } // BeforeAdjustmentAmount10
        public decimal? AfterAdjustmentAmount10 { get; set; } // AfterAdjustmentAmount10
        public decimal? BeforeAdjustmentAmount11 { get; set; } // BeforeAdjustmentAmount11
        public decimal? AfterAdjustmentAmount11 { get; set; } // AfterAdjustmentAmount11
        public decimal? BeforeAdjustmentAmount12 { get; set; } // BeforeAdjustmentAmount12
        public decimal? AfterAdjustmentAmount12 { get; set; } // AfterAdjustmentAmount12
        public string Remark { get; set; } // Remark (length: 500)
        public System.DateTime? AdjustmentDate { get; set; } // AdjustmentDate
        public string AdjustmentUser { get; set; } // AdjustmentUser (length: 50)
        public string AdjustmentUserName { get; set; } // AdjustmentUserName (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
