// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Budget_Item
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetItem : Entity<Guid>
    {
        public string BudgetItemId { get; set; } // BudgetItemID (Primary key) (length: 50)
        public string UpperBudgetItemId { get; set; } // UpperBudgetItemID (length: 50)
        public string BudgetItemCode { get; set; } // BudgetItemCode (length: 50)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public decimal? TaxRate { get; set; } // TaxRate
        public string BudgetDesc { get; set; } // BudgetDesc (length: 1000)
        public int? IsInvalid { get; set; } // IsInvalid
        public System.DateTime? AvailabilityDate { get; set; } // AvailabilityDate
        public System.DateTime? ExpiryDate { get; set; } // ExpiryDate
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? OrderIndex { get; set; } // OrderIndex
        public int? PlanModify { get; set; } // PlanModify
        public int? FactModify { get; set; } // FactModify
        public string ManageType { get; set; } // ManageType (length: 10)
        public string BudgetTypeId { get; set; } // BudgetTypeID (length: 50)
        public int? ItemType { get; set; } // ItemType
        public int? IsMaterial { get; set; } // IsMaterial
        public string AccountCode { get; set; } // AccountCode (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetAccountingRelates where [TB_Budget_Accounting_Relate].[BudgetItemID] point to this entity (RefTB_Budget_Item27)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetAccountingRelate> TbBudgetAccountingRelates { get; set; } // TB_Budget_Accounting_Relate.RefTB_Budget_Item27
        /// <summary>
        /// Child TbBudgetBaseInfoRelates where [TB_BudgetBaseInfo_Relate].[BudgetItemID] point to this entity (RefTB_Budget_Item343)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetBaseInfoRelate> TbBudgetBaseInfoRelates { get; set; } // TB_BudgetBaseInfo_Relate.RefTB_Budget_Item343
        /// <summary>
        /// Child TbBudgetControlDetails where [TB_Budget_Control_Detail].[BudgetItemID] point to this entity (RefTB_Budget_Item167)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetControlDetail> TbBudgetControlDetails { get; set; } // TB_Budget_Control_Detail.RefTB_Budget_Item167
        /// <summary>
        /// Child TbBudgetItemSubTypeRelates where [TB_Budget_Item_SubType_Relate].[BudgetItemID] point to this entity (FK_Budget_Item)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetItemSubTypeRelate> TbBudgetItemSubTypeRelates { get; set; } // TB_Budget_Item_SubType_Relate.FK_Budget_Item
        /// <summary>
        /// Child TbMonthlyPayPlanBudgetItemsDrafts where [TB_Monthly_PayPlan_BudgetItems_Draft].[BudgetItemID] point to this entity (RefTB_Budget_Item103)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbMonthlyPayPlanBudgetItemsDraft> TbMonthlyPayPlanBudgetItemsDrafts { get; set; } // TB_Monthly_PayPlan_BudgetItems_Draft.RefTB_Budget_Item103
        /// <summary>
        /// Child TbPlanApplies where [TB_Plan_Apply].[BudgetItemID] point to this entity (RefTB_Budget_Item237)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbPlanApply> TbPlanApplies { get; set; } // TB_Plan_Apply.RefTB_Budget_Item237

        public TbBudgetItem()
        {
            TbBudgetAccountingRelates = new System.Collections.Generic.List<TbBudgetAccountingRelate>();
            TbBudgetControlDetails = new System.Collections.Generic.List<TbBudgetControlDetail>();
            TbBudgetItemSubTypeRelates = new System.Collections.Generic.List<TbBudgetItemSubTypeRelate>();
            TbBudgetBaseInfoRelates = new System.Collections.Generic.List<TbBudgetBaseInfoRelate>();
            TbMonthlyPayPlanBudgetItemsDrafts = new System.Collections.Generic.List<TbMonthlyPayPlanBudgetItemsDraft>();
            TbPlanApplies = new System.Collections.Generic.List<TbPlanApply>();
        }
    }

}
// </auto-generated>
