// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_BudgetBaseInfo_Relate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetBaseInfoRelate : Entity<Guid>
    {
        public string RelateId { get; set; } // RelateID (Primary key) (length: 50)
        public string ProjetName { get; set; } // ProjetName (length: 50)
        public string ProjectId { get; set; } // ProjectID (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockName { get; set; } // BlockName (length: 50)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string CostCenterCode { get; set; } // CostCenterCode (length: 50)
        public string CostCenterName { get; set; } // CostCenterName (length: 50)
        public string BudgetTypeId { get; set; } // BudgetTypeID (length: 50)
        public string BudgetTypeName { get; set; } // BudgetTypeName (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string BudgetItemCode { get; set; } // BudgetItemCode (length: 50)
        public System.DateTime? ServiceEndDate { get; set; } // ServiceEndDate
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public System.DateTime? ServiceStartDate { get; set; } // ServiceStartDate
        public string OrgUnitCode { get; set; } // OrgUnitCode (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public string OrgUnitName { get; set; } // OrgUnitName (length: 50)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public string F1 { get; set; } // F1 (length: 50)
        public string F2 { get; set; } // F2 (length: 50)
        public string F3 { get; set; } // F3 (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbBlock pointed by [TB_BudgetBaseInfo_Relate].([BlockId]) (RefTB_Block342)
        /// </summary>
        public virtual TbBlock TbBlock { get; set; } // RefTB_Block342

        /// <summary>
        /// Parent TbBudgetItem pointed by [TB_BudgetBaseInfo_Relate].([BudgetItemId]) (RefTB_Budget_Item343)
        /// </summary>
        public virtual TbBudgetItem TbBudgetItem { get; set; } // RefTB_Budget_Item343

        /// <summary>
        /// Parent TbCostCenter pointed by [TB_BudgetBaseInfo_Relate].([CostCenterId]) (RefTB_CostCenter344)
        /// </summary>
        public virtual TbCostCenter TbCostCenter { get; set; } // RefTB_CostCenter344
    }

}
// </auto-generated>
