// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_BudgetSubType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetSubType : Entity<Guid>
    {
        public string BudgetSubTypeId { get; set; } // BudgetSubTypeID (Primary key) (length: 50)
        public string BudgetTypeId { get; set; } // BudgetTypeID (length: 50)
        public string BudgetSubTypeCode { get; set; } // BudgetSubTypeCode (length: 20)
        public string BudgetSubTypeName { get; set; } // BudgetSubTypeName (length: 50)
        public string BudgetsubtypeDesc { get; set; } // BudgetsubtypeDesc (length: 1073741823)
        public int? IsNeedContract { get; set; } // IsNeedContract
        public int? IsNeedPay { get; set; } // IsNeedPay
        public string ContractAttachmentDesc { get; set; } // ContractAttachmentDesc (length: 1000)
        public int? IsInvalid { get; set; } // IsInvalid
        public System.DateTime? AvailabilityDate { get; set; } // AvailabilityDate
        public System.DateTime? ExpiryDate { get; set; } // ExpiryDate
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? OrderIndex { get; set; } // OrderIndex
        public int? FixedPayDate { get; set; } // FixedPayDate
        public int? IsNeedAgreement { get; set; } // IsNeedAgreement
        public string ManagerType { get; set; } // ManagerType (length: 10)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetItemSubTypeRelates where [TB_Budget_Item_SubType_Relate].[BudgetSubTypeID] point to this entity (FK__BudgetSubType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetItemSubTypeRelate> TbBudgetItemSubTypeRelates { get; set; } // TB_Budget_Item_SubType_Relate.FK__BudgetSubType
        /// <summary>
        /// Child TbCostCenterBudgetSubTypeRelates where [TB_CostCenter_BudgetSubType_Relate].[BudgetSubTypeID] point to this entity (RefTB_BudgetSubType35)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbCostCenterBudgetSubTypeRelate> TbCostCenterBudgetSubTypeRelates { get; set; } // TB_CostCenter_BudgetSubType_Relate.RefTB_BudgetSubType35
        /// <summary>
        /// Child TbTemplateBudgetRelates where [TB_Template_Budget_Relate].[BudgetSubTypeID] point to this entity (RefTB_BudgetSubType155)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbTemplateBudgetRelate> TbTemplateBudgetRelates { get; set; } // TB_Template_Budget_Relate.RefTB_BudgetSubType155

        // Foreign keys

        /// <summary>
        /// Parent TbBudgetType pointed by [TB_BudgetSubType].([BudgetTypeId]) (RefTB_BudgetType28)
        /// </summary>
        public virtual TbBudgetType TbBudgetType { get; set; } // RefTB_BudgetType28

        public TbBudgetSubType()
        {
            TbBudgetItemSubTypeRelates = new System.Collections.Generic.List<TbBudgetItemSubTypeRelate>();
            TbCostCenterBudgetSubTypeRelates = new System.Collections.Generic.List<TbCostCenterBudgetSubTypeRelate>();
            TbTemplateBudgetRelates = new System.Collections.Generic.List<TbTemplateBudgetRelate>();
        }
    }

}
// </auto-generated>
