// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Budget_Adjustment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetAdjustment : Entity<Guid>
    {
        public string AdjustmentId { get; set; } // AdjustmentID (Primary key) (length: 50)
        public string AdjustmentCode { get; set; } // AdjustmentCode (length: 50)
        public string InBlockId { get; set; } // InBlockID (length: 50)
        public string InBlockName { get; set; } // InBlockName (length: 100)
        public string InCostCenterId { get; set; } // InCostCenterID (length: 50)
        public string InCostCenterName { get; set; } // InCostCenterName (length: 100)
        public decimal InTotalAmount { get; set; } // InTotalAmount
        public string OutBlockId { get; set; } // OutBlockID (length: 50)
        public string OutBlockName { get; set; } // OutBlockName (length: 100)
        public string OutCostCenterId { get; set; } // OutCostCenterID (length: 50)
        public string OutCostCenterName { get; set; } // OutCostCenterName (length: 100)
        public decimal? OutTotalAmount { get; set; } // OutTotalAmount
        public int AdjustmentType { get; set; } // AdjustmentType
        public int Status { get; set; } // Status
        public string ProcInstId { get; set; } // ProcInstID (length: 50)
        public System.DateTime CreateDate { get; set; } // CreateDate
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime? ModiftyDate { get; set; } // ModiftyDate
        public string ModiftyUser { get; set; } // ModiftyUser (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? InMonth { get; set; } // InMonth
        public int? OutMonth { get; set; } // OutMonth

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetAdjustmentDetails where [TB_Budget_Adjustment_Detail].[AdjustmentID] point to this entity (RefTB_Budget_Adjustment309)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetAdjustmentDetail> TbBudgetAdjustmentDetails { get; set; } // TB_Budget_Adjustment_Detail.RefTB_Budget_Adjustment309
        /// <summary>
        /// Child TbBudgetPlanCostCenterMonthDetailV2 where [TB_Budget_Plan_CostCenter_MonthDetail_V2].[AdjustmentID] point to this entity (RefTB_Budget_Adjustment2421)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanCostCenterMonthDetailV2> TbBudgetPlanCostCenterMonthDetailV2 { get; set; } // TB_Budget_Plan_CostCenter_MonthDetail_V2.RefTB_Budget_Adjustment2421

        public TbBudgetAdjustment()
        {
            TbBudgetAdjustmentDetails = new System.Collections.Generic.List<TbBudgetAdjustmentDetail>();
            TbBudgetPlanCostCenterMonthDetailV2 = new System.Collections.Generic.List<TbBudgetPlanCostCenterMonthDetailV2>();
        }
    }

}
// </auto-generated>
