// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_BusinessExecution_Detail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBusinessExecutionDetail : Entity<Guid>
    {
        public string ExecutionDetailId { get; set; } // ExecutionDetailID (Primary key) (length: 50)
        public string BusinessExecutionId { get; set; } // BusinessExecutionID (length: 50)
        public string PerformancePlanId { get; set; } // PerformancePlanID (length: 50)
        public System.DateTime? ServiceStartDate { get; set; } // ServiceStartDate
        public System.DateTime? ServiceEndDate { get; set; } // ServiceEndDate
        public string ItemDetail { get; set; } // ItemDetail (length: 100)
        public decimal? ConfirmationAmount { get; set; } // ConfirmationAmount
        public decimal? PeriodConfirmationAmount { get; set; } // PeriodConfirmationAmount
        public decimal? ServiceAmount { get; set; } // ServiceAmount
        public string Explain { get; set; } // Explain (length: 500)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbBusinessExecution pointed by [TB_BusinessExecution_Detail].([BusinessExecutionId]) (RefTB_BusinessExecution339)
        /// </summary>
        public virtual TbBusinessExecution TbBusinessExecution { get; set; } // RefTB_BusinessExecution339
    }

}
// </auto-generated>
