// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_BusinessExecution
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBusinessExecution : Entity<Guid>
    {
        public string BusinessExecutionId { get; set; } // BusinessExecutionID (Primary key) (length: 50)
        public string BusinessExecutionCode { get; set; } // BusinessExecutionCode (length: 50)
        public string BusinessExecutionName { get; set; } // BusinessExecutionName (length: 50)
        public decimal? PeriodConfirmationAmount { get; set; } // PeriodConfirmationAmount
        public decimal? TotalAmount { get; set; } // TotalAmount
        public string ProjectId { get; set; } // ProjectID (length: 50)
        public string ProjectName { get; set; } // ProjectName (length: 100)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockName { get; set; } // BlockName (length: 50)
        public string SupplierId { get; set; } // SupplierID (length: 50)
        public string CompanyName { get; set; } // CompanyName (length: 100)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public string BudgetDeptId { get; set; } // BudgetDeptID (length: 50)
        public string BudgetDept { get; set; } // BudgetDept (length: 50)
        public string PlanApplyId { get; set; } // PlanApplyID (length: 50)
        public string PlanApplyName { get; set; } // PlanApplyName (length: 100)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string ContractName { get; set; } // ContractName (length: 100)
        public int? IsVisible { get; set; } // IsVisible
        public string AttnId { get; set; } // AttnID (length: 50)
        public string AttnName { get; set; } // AttnName (length: 50)
        public string AttnDeptId { get; set; } // AttnDeptID (length: 50)
        public string AttnDeptName { get; set; } // AttnDeptName (length: 50)
        public string ExecutionDesc { get; set; } // ExecutionDesc (length: 1073741823)
        public int? Status { get; set; } // Status
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string LatestApprover { get; set; } // LatestApprover (length: 50)
        public string LatestComment { get; set; } // LatestComment
        public System.DateTime? LatestApproveTime { get; set; } // LatestApproveTime
        public string Procinstid { get; set; } // Procinstid (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? FormType { get; set; } // FormType
        public string CorporateGuid { get; set; } // CorporateGUID (length: 50)
        public string CorporateCode { get; set; } // CorporateCode (length: 100)
        public string CorporateName { get; set; } // CorporateName (length: 100)
        public string OriginalBusinessExecutionCode { get; set; } // OriginalBusinessExecutionCode (length: 50)
        public System.DateTime? PostDateTime { get; set; } // PostDateTime
        public string AssociatedConfirmationsSlipId { get; set; } // AssociatedConfirmationsSlipID (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBusinessExecutionDetails where [TB_BusinessExecution_Detail].[BusinessExecutionID] point to this entity (RefTB_BusinessExecution339)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBusinessExecutionDetail> TbBusinessExecutionDetails { get; set; } // TB_BusinessExecution_Detail.RefTB_BusinessExecution339
        /// <summary>
        /// Child TbMaterialsDetails where [TB_Materials_Detail].[BusinessExecutionID] point to this entity (RefTB_BusinessExecution340)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbMaterialsDetail> TbMaterialsDetails { get; set; } // TB_Materials_Detail.RefTB_BusinessExecution340
        /// <summary>
        /// Child TbMaterialsRecipients where [TB_Materials_Recipients].[BusinessExecutionID] point to this entity (RefTB_BusinessExecution341)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbMaterialsRecipient> TbMaterialsRecipients { get; set; } // TB_Materials_Recipients.RefTB_BusinessExecution341

        public TbBusinessExecution()
        {
            TbBusinessExecutionDetails = new System.Collections.Generic.List<TbBusinessExecutionDetail>();
            TbMaterialsDetails = new System.Collections.Generic.List<TbMaterialsDetail>();
            TbMaterialsRecipients = new System.Collections.Generic.List<TbMaterialsRecipient>();
        }
    }

}
// </auto-generated>
