// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_BudgetVersionType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbBudgetVersionType : Entity<Guid>
    {
        public string VersionTypeId { get; set; } // VersionTypeID (Primary key) (length: 50)
        public string VersionTypeCode { get; set; } // VersionTypeCode (length: 20)
        public string VersionTypeName { get; set; } // VersionTypeName (length: 50)
        public int? IsMappingVersion { get; set; } // IsMappingVersion
        public int? IsAllowAdjust { get; set; } // IsAllowAdjust
        public string Desc { get; set; } // Desc (length: 1000)
        public int? Order { get; set; } // Order
        public int? IsInvalid { get; set; } // IsInvalid
        public System.DateTime? AvailabilityDate { get; set; } // AvailabilityDate
        public System.DateTime? ExpiryDate { get; set; } // ExpiryDate
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetPlanVersionV1 where [TB_Budget_Plan_Version_V1].[VersionTypeID] point to this entity (RefTB_BudgetVersionType297)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanVersionV1> TbBudgetPlanVersionV1 { get; set; } // TB_Budget_Plan_Version_V1.RefTB_BudgetVersionType297
        /// <summary>
        /// Child TbBudgetPlanVersionV2 where [TB_Budget_Plan_Version_V2].[VersionTypeID] point to this entity (RefTB_BudgetVersionType381)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanVersionV2> TbBudgetPlanVersionV2 { get; set; } // TB_Budget_Plan_Version_V2.RefTB_BudgetVersionType381

        public TbBudgetVersionType()
        {
            TbBudgetPlanVersionV1 = new System.Collections.Generic.List<TbBudgetPlanVersionV1>();
            TbBudgetPlanVersionV2 = new System.Collections.Generic.List<TbBudgetPlanVersionV2>();
        }
    }

}
// </auto-generated>
