// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'TB_Contract_LoanSign' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // TB_Contract_LoanSign
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbContractLoanSign : Entity<Guid>
    {
        public string LoanId { get; set; } // LoanID (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public decimal? Amount { get; set; } // Amount
        public string Creator { get; set; } // Creator (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string F1 { get; set; } // F1 (length: 100)
        public string F2 { get; set; } // F2 (length: 100)
        public string F3 { get; set; } // F3 (length: 100)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
