// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Contract
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbContract : Entity<Guid>
    {
        public string ContractId { get; set; } // ContractID (Primary key) (length: 50)
        public string BudgetSubTypeId { get; set; } // BudgetSubTypeID (length: 50)
        public string CorporateGuid { get; set; } // CorporateGUID (length: 50)
        public string ContractCode { get; set; } // ContractCode (length: 50)
        public string ContractName { get; set; } // ContractName (length: 100)
        public decimal? ContractAmount { get; set; } // ContractAmount
        public decimal? ContractTotalAmount { get; set; } // ContractTotalAmount
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockName { get; set; } // BlockName (length: 50)
        public int? IsPagingSeal { get; set; } // IsPagingSeal
        public string ContractType { get; set; } // ContractType (length: 50)
        public string ContractTypeName { get; set; } // ContractTypeName (length: 50)
        public string PlanApplyId { get; set; } // PlanApplyID (length: 50)
        public string PlanApplyName { get; set; } // PlanApplyName (length: 50)
        public decimal? RemainingAmount { get; set; } // RemainingAmount
        public string ContractNature { get; set; } // ContractNature (length: 50)
        public string ContractNatureName { get; set; } // ContractNatureName (length: 50)
        public System.DateTime? SignDate { get; set; } // SignDate
        public System.DateTime? StartTime { get; set; } // StartTime
        public System.DateTime? EndTime { get; set; } // EndTime
        public int? IsPrint { get; set; } // IsPrint
        public int? BiddingMethod { get; set; } // BiddingMethod
        public string BiddingMethodName { get; set; } // BiddingMethodName (length: 50)
        public decimal? TotalTax { get; set; } // TotalTax
        public decimal? TotalExcludingTax { get; set; } // TotalExcludingTax
        public decimal? PaidAmount { get; set; } // PaidAmount
        public int? IsAmendTerms { get; set; } // IsAmendTerms
        public string CorporateName { get; set; } // CorporateName (length: 50)
        public string CorporateCode { get; set; } // CorporateCode (length: 50)
        public string SecondPartyName { get; set; } // SecondPartyName (length: 50)
        public string SecondPartyCode { get; set; } // SecondPartyCode (length: 50)
        public string ThirdPartyName { get; set; } // ThirdPartyName (length: 50)
        public string ThirdPartyCode { get; set; } // ThirdPartyCode (length: 50)
        public string FourthPartyName { get; set; } // FourthPartyName (length: 50)
        public string FourthPartyCode { get; set; } // FourthPartyCode (length: 50)
        public string FifthPartyName { get; set; } // FifthPartyName (length: 50)
        public string FifthPartyCode { get; set; } // FifthPartyCode (length: 50)
        public string ContractDesc { get; set; } // ContractDesc (length: 1073741823)
        public string PriceExplanation { get; set; } // PriceExplanation (length: 1073741823)
        public int? Status { get; set; } // Status
        public int? PayStatus { get; set; } // PayStatus
        public string ProcInstId { get; set; } // ProcInstID (length: 50)
        public string LatestApprover { get; set; } // LatestApprover (length: 50)
        public string LatestComment { get; set; } // LatestComment (length: 1000)
        public System.DateTime? LatestApproveTime { get; set; } // LatestApproveTime
        public string Creator { get; set; } // Creator (length: 50)
        public string CreatorLoginId { get; set; } // CreatorLoginID (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string CreatorDeptId { get; set; } // CreatorDeptID (length: 50)
        public string CreatorDeptName { get; set; } // CreatorDeptName (length: 50)
        public string CreatorOrgUnitGuid { get; set; } // CreatorOrgUnitGuid (length: 50)
        public string CreatorOrgUnitName { get; set; } // CreatorOrgUnitName (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string UpdateUserName { get; set; } // UpdateUserName (length: 50)
        public string UpdateUserDeptId { get; set; } // UpdateUserDeptID (length: 50)
        public string UpdateUserDeptName { get; set; } // UpdateUserDeptName (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string IsFrameworkContract { get; set; } // IsFrameworkContract (length: 10)
        public string MainContractId { get; set; } // MainContractID (length: 50)
        public string FullName { get; set; } // FullName (length: 500)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public string SecCompanyCode { get; set; } // SecCompanyCode (length: 50)
        public string IsStandardContract { get; set; } // IsStandardContract (length: 10)
        public string Principal { get; set; } // Principal (length: 50)
        public decimal? CurrentContractAmount { get; set; } // CurrentContractAmount
        public decimal? TaxCurrentAmount { get; set; } // TaxCurrentAmount
        public string Islocked { get; set; } // islocked (length: 10)
        public string ContractFlag { get; set; } // ContractFlag (length: 10)
        public string VatType { get; set; } // VATType (length: 10)
        public decimal? TotalTaxes { get; set; } // TotalTaxes
        public string BudgetSubTypeName { get; set; } // BudgetSubTypeName (length: 50)
        public string Reason { get; set; } // Reason (length: 1000)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? IsFixed { get; set; } // IsFixed
        public string Fixed { get; set; } // Fixed (length: 50)
        public string OriginalContractCode { get; set; } // OriginalContractCode (length: 50)
        public string PayCompanyGuid { get; set; } // PayCompanyGuid (length: 50)
        public string PayCompanyName { get; set; } // PayCompanyName (length: 50)
        public string PayCompanyCode { get; set; } // PayCompanyCode (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbContractDetails where [TB_Contract_Detail].[ContractID] point to this entity (RefTB_Contract51)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbContractDetail> TbContractDetails { get; set; } // TB_Contract_Detail.RefTB_Contract51
        /// <summary>
        /// Child TbContractPayPlans where [TB_Contract_PayPlan].[ContractID] point to this entity (RefTB_Contract55)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbContractPayPlan> TbContractPayPlans { get; set; } // TB_Contract_PayPlan.RefTB_Contract55
        /// <summary>
        /// Child TbContractRelatePlans where [TB_Contract_RelatePlan].[ContractID] point to this entity (RefTB_Contract3381)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbContractRelatePlan> TbContractRelatePlans { get; set; } // TB_Contract_RelatePlan.RefTB_Contract3381
        /// <summary>
        /// Child TbContractSelects where [TB_Contract_Select].[ContractID] point to this entity (RefTB_Contract244)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbContractSelect> TbContractSelects { get; set; } // TB_Contract_Select.RefTB_Contract244
        /// <summary>
        /// Child TbContractStatistics where [TB_Contract_Statistics].[ContractID] point to this entity (RefTB_Contract84)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbContractStatistic> TbContractStatistics { get; set; } // TB_Contract_Statistics.RefTB_Contract84

        public TbContract()
        {
            TbContractDetails = new System.Collections.Generic.List<TbContractDetail>();
            TbContractPayPlans = new System.Collections.Generic.List<TbContractPayPlan>();
            TbContractRelatePlans = new System.Collections.Generic.List<TbContractRelatePlan>();
            TbContractSelects = new System.Collections.Generic.List<TbContractSelect>();
            TbContractStatistics = new System.Collections.Generic.List<TbContractStatistic>();
        }
    }

}
// </auto-generated>
