// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_CostCenter
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbCostCenter : Entity<Guid>
    {
        public string CostCenterId { get; set; } // CostCenterID (Primary key) (length: 50)
        public string UpperCostCenterId { get; set; } // UpperCostCenterID (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public int? CostCenterType { get; set; } // CostCenterType
        public string CostCenterCode { get; set; } // CostCenterCode (length: 50)
        public string CostCenterName { get; set; } // CostCenterName (length: 50)
        public int? IsInvalid { get; set; } // IsInvalid
        public string Remark { get; set; } // Remark (length: 1000)
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? OrderIndex { get; set; } // OrderIndex
        public string CostCenterAlias { get; set; } // CostCenterAlias (length: 50)
        public string ManageType { get; set; } // ManageType (length: 10)
        public string ManagerType { get; set; } // ManagerType (length: 10)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbBudgetBaseInfoRelates where [TB_BudgetBaseInfo_Relate].[CostCenterID] point to this entity (RefTB_CostCenter344)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetBaseInfoRelate> TbBudgetBaseInfoRelates { get; set; } // TB_BudgetBaseInfo_Relate.RefTB_CostCenter344
        /// <summary>
        /// Child TbBudgetPlanCostCenters where [TB_Budget_Plan_CostCenter].[CostCenterID] point to this entity (RefTB_CostCenter62)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanCostCenter> TbBudgetPlanCostCenters { get; set; } // TB_Budget_Plan_CostCenter.RefTB_CostCenter62
        /// <summary>
        /// Child TbBudgetPlanCostCenterV1 where [TB_Budget_Plan_CostCenter_V1].[CostCenterID] point to this entity (RefTB_CostCenter1131)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanCostCenterV1> TbBudgetPlanCostCenterV1 { get; set; } // TB_Budget_Plan_CostCenter_V1.RefTB_CostCenter1131
        /// <summary>
        /// Child TbBudgetPlanCostCenterV2 where [TB_Budget_Plan_CostCenter_V2].[CostCenterID] point to this entity (RefTB_CostCenter621)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbBudgetPlanCostCenterV2> TbBudgetPlanCostCenterV2 { get; set; } // TB_Budget_Plan_CostCenter_V2.RefTB_CostCenter621
        /// <summary>
        /// Child TbCostCenterBudgetSubTypeRelates where [TB_CostCenter_BudgetSubType_Relate].[CostCenterID] point to this entity (RefTB_CostCenter61)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbCostCenterBudgetSubTypeRelate> TbCostCenterBudgetSubTypeRelates { get; set; } // TB_CostCenter_BudgetSubType_Relate.RefTB_CostCenter61
        /// <summary>
        /// Child TbMonthlyPayPlanCostCenters where [TB_Monthly_PayPlan_CostCenter].[CostCenterID] point to this entity (RefTB_CostCenter67)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbMonthlyPayPlanCostCenter> TbMonthlyPayPlanCostCenters { get; set; } // TB_Monthly_PayPlan_CostCenter.RefTB_CostCenter67
        /// <summary>
        /// Child TbMonthlyPayPlanCostCenterDrafts where [TB_Monthly_PayPlan_CostCenter_Draft].[CostCenterID] point to this entity (RefTB_CostCenter102)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbMonthlyPayPlanCostCenterDraft> TbMonthlyPayPlanCostCenterDrafts { get; set; } // TB_Monthly_PayPlan_CostCenter_Draft.RefTB_CostCenter102
        /// <summary>
        /// Child TbPlanApplies where [TB_Plan_Apply].[CostCenterID] point to this entity (RefTB_CostCenter239)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbPlanApply> TbPlanApplies { get; set; } // TB_Plan_Apply.RefTB_CostCenter239

        public TbCostCenter()
        {
            TbBudgetPlanCostCenters = new System.Collections.Generic.List<TbBudgetPlanCostCenter>();
            TbBudgetPlanCostCenterV1 = new System.Collections.Generic.List<TbBudgetPlanCostCenterV1>();
            TbBudgetPlanCostCenterV2 = new System.Collections.Generic.List<TbBudgetPlanCostCenterV2>();
            TbBudgetBaseInfoRelates = new System.Collections.Generic.List<TbBudgetBaseInfoRelate>();
            TbCostCenterBudgetSubTypeRelates = new System.Collections.Generic.List<TbCostCenterBudgetSubTypeRelate>();
            TbMonthlyPayPlanCostCenters = new System.Collections.Generic.List<TbMonthlyPayPlanCostCenter>();
            TbMonthlyPayPlanCostCenterDrafts = new System.Collections.Generic.List<TbMonthlyPayPlanCostCenterDraft>();
            TbPlanApplies = new System.Collections.Generic.List<TbPlanApply>();
        }
    }

}
// </auto-generated>
