// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Contract_Detail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbContractDetail : Entity<Guid>
    {
        public string ContractDetailId { get; set; } // ContractDetailID (Primary key) (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string MainContractDetailId { get; set; } // MainContractDetailID (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public string OrgUnitName { get; set; } // OrgUnitName (length: 50)
        public string SupplierId { get; set; } // SupplierID (length: 50)
        public string SupplierName { get; set; } // SupplierName (length: 50)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string CostCenterCode { get; set; } // CostCenterCode (length: 50)
        public string CostCenterName { get; set; } // CostCenterName (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockName { get; set; } // BlockName (length: 50)
        public System.DateTime? BudgetRangeStart { get; set; } // BudgetRangeStart
        public System.DateTime? BudgetRangeEnd { get; set; } // BudgetRangeEnd
        public decimal? ApplyAmount { get; set; } // ApplyAmount
        public decimal? MainApplyAmount { get; set; } // MainApplyAmount
        public decimal? AvailableCredit { get; set; } // AvailableCredit
        public decimal? TaxRate { get; set; } // TaxRate
        public decimal? Tax { get; set; } // Tax
        public decimal? ExcludingTax { get; set; } // ExcludingTax
        public decimal? FinancialTax { get; set; } // FinancialTax
        public int? InvoiceType { get; set; } // InvoiceType
        public string InvoiceTypeName { get; set; } // InvoiceTypeName (length: 10)
        public int? RowNumber { get; set; } // RowNumber
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public decimal? BudgetAmount { get; set; } // BudgetAmount
        public decimal? PaidAmount { get; set; } // PaidAmount
        public decimal? ApprovedNoPaidAmount { get; set; } // ApprovedNoPaidAmount
        public decimal? ApprovingApplyAmount { get; set; } // ApprovingApplyAmount
        public decimal? WaittingSubmitAmount { get; set; } // WaittingSubmitAmount
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbContract pointed by [TB_Contract_Detail].([ContractId]) (RefTB_Contract51)
        /// </summary>
        public virtual TbContract TbContract { get; set; } // RefTB_Contract51
    }

}
// </auto-generated>
