// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Contract_Select
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbContractSelect : Entity<Guid>
    {
        public string SelectId { get; set; } // SelectID (Primary key) (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string ContractType { get; set; } // ContractType (length: 50)
        public string ContractTypeName { get; set; } // ContractTypeName (length: 50)
        public string ContractBigType { get; set; } // ContractBigType (length: 50)
        public string ContractBigTypeName { get; set; } // ContractBigTypeName (length: 50)
        public string ContractSmallType { get; set; } // ContractSmallType (length: 50)
        public string ContractSmallTypeName { get; set; } // ContractSmallTypeName (length: 50)
        public string IsStandardContract { get; set; } // IsStandardContract (length: 50)
        public string IsStandardContractName { get; set; } // IsStandardContractName (length: 50)
        public string ContractTemplateId { get; set; } // ContractTemplateID (length: 50)
        public string NotStandardContractReason { get; set; } // NotStandardContractReason (length: 500)
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbContract pointed by [TB_Contract_Select].([ContractId]) (RefTB_Contract244)
        /// </summary>
        public virtual TbContract TbContract { get; set; } // RefTB_Contract244
    }

}
// </auto-generated>
