// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Contract_Attachment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbContractAttachment : Entity<Guid>
    {
        public string ContractAttachmentId { get; set; } // ContractAttachmentID (Primary key) (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string AttachmentName { get; set; } // AttachmentName (length: 200)
        public string AttachmentSuffix { get; set; } // AttachmentSuffix (length: 10)
        public string AttachmentUrl { get; set; } // AttachmentUrl (length: 200)
        public System.DateTime? UploadDate { get; set; } // UploadDate
        public int? AttachmenType { get; set; } // AttachmenType
        public string Content { get; set; } // Content (length: 1073741823)
        public string StandardContractId { get; set; } // StandardContractID (length: 50)
        public string ControlId { get; set; } // ControlID (length: 50)
        public string VisionContent { get; set; } // VisionContent (length: 1073741823)
        public string SummaryContent { get; set; } // SummaryContent (length: 1073741823)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
