// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Corporate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbCorporate : Entity<Guid>
    {
        public string CorporateGuid { get; set; } // CorporateGUID (Primary key) (length: 50)
        public string CorporateCode { get; set; } // CorporateCode (length: 100)
        public string CorporateName { get; set; } // CorporateName (length: 100)
        public string CorporateDesc { get; set; } // CorporateDesc (length: 1000)
        public int? IsInvalid { get; set; } // IsInvalid
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? OrderIndex { get; set; } // OrderIndex
        public int? VatType { get; set; } // VATType

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbCorporateBankAccounts where [TB_Corporate_BankAccount].[CorporateGUID] point to this entity (RefTB_Corporate46)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbCorporateBankAccount> TbCorporateBankAccounts { get; set; } // TB_Corporate_BankAccount.RefTB_Corporate46

        public TbCorporate()
        {
            TbCorporateBankAccounts = new System.Collections.Generic.List<TbCorporateBankAccount>();
        }
    }

}
// </auto-generated>
