// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Contract_RelatePlan
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbContractRelatePlan : Entity<Guid>
    {
        public string ContractRelatePlanId { get; set; } // ContractRelatePlanID (Primary key) (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string PlanApplyId { get; set; } // PlanApplyID (length: 50)
        public string PlanApplyDetailId { get; set; } // PlanApplyDetailID (length: 50)
        public decimal Amount { get; set; } // Amount
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbContract pointed by [TB_Contract_RelatePlan].([ContractId]) (RefTB_Contract3381)
        /// </summary>
        public virtual TbContract TbContract { get; set; } // RefTB_Contract3381
    }

}
// </auto-generated>
