// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Contract_Template
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbContractTemplate : Entity<Guid>
    {
        public string ContractTemplateId { get; set; } // ContractTemplateID (Primary key) (length: 50)
        public string ContractTemplateName { get; set; } // ContractTemplateName (length: 50)
        public string TemplateContent { get; set; } // TemplateContent (length: 1073741823)
        public int? IsInvalid { get; set; } // IsInvalid
        public System.DateTime? AvailabilityDate { get; set; } // AvailabilityDate
        public System.DateTime? ExpiryDate { get; set; } // ExpiryDate
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string BudgetSubTypeId { get; set; } // BudgetSubTypeID (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public string CompliancePlanTableName { get; set; } // CompliancePlanTableName (length: 1000)
        public string FilePath { get; set; } // FilePath (length: 200)
        public string TemplateType { get; set; } // TemplateType (length: 50)
        public int? OrderIndex { get; set; } // OrderIndex
        public string AppId { get; set; } // AppID (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbStandardContractContents where [TB_StandardContractContent].[ContractTemplateID] point to this entity (RefTB_Contract_Template171)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbStandardContractContent> TbStandardContractContents { get; set; } // TB_StandardContractContent.RefTB_Contract_Template171
        /// <summary>
        /// Child TbTemplateBudgetRelates where [TB_Template_Budget_Relate].[ContractTemplateID] point to this entity (RefTB_Contract_Template153)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbTemplateBudgetRelate> TbTemplateBudgetRelates { get; set; } // TB_Template_Budget_Relate.RefTB_Contract_Template153

        public TbContractTemplate()
        {
            TbStandardContractContents = new System.Collections.Generic.List<TbStandardContractContent>();
            TbTemplateBudgetRelates = new System.Collections.Generic.List<TbTemplateBudgetRelate>();
        }
    }

}
// </auto-generated>
