// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Dept_Category
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbDeptCategory : Entity<Guid>
    {
        public string DeptCategoryId { get; set; } // DeptCategoryID (Primary key) (length: 50)
        public string DeptCategoryName { get; set; } // DeptCategoryName (length: 50)
        public int? Status { get; set; } // Status
        public string Creator { get; set; } // Creator (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string UpdateUserName { get; set; } // UpdateUserName (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbDeptCategoryRelates where [TB_Dept_Category_Relate].[DeptCategoryID] point to this entity (RefTB_Dept_Category346)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbDeptCategoryRelate> TbDeptCategoryRelates { get; set; } // TB_Dept_Category_Relate.RefTB_Dept_Category346

        public TbDeptCategory()
        {
            TbDeptCategoryRelates = new System.Collections.Generic.List<TbDeptCategoryRelate>();
        }
    }

}
// </auto-generated>
