// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_FinancialDesk_1220
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbFinancialDesk1220 : Entity<Guid>
    {
        public string FinancialDeskId { get; set; } // FinancialDeskID (Primary key) (length: 50)
        public decimal Version { get; set; } // Version (Primary key)
        public string CostTypeCode { get; set; } // CostTypeCode (length: 150)
        public string CostTypeName { get; set; } // CostTypeName (length: 150)
        public string ProjectId { get; set; } // ProjectID (length: 50)
        public string ProjectCode { get; set; } // ProjectCode (length: 150)
        public string ProjectName { get; set; } // ProjectName (length: 150)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockCode { get; set; } // BlockCode (length: 150)
        public string BlockName { get; set; } // BlockName (length: 150)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string CostCenterCode { get; set; } // CostCenterCode (length: 150)
        public string CostCenterName { get; set; } // CostCenterName (length: 150)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string BudgetItemCode { get; set; } // BudgetItemCode (length: 150)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 150)
        public string CorporateGuid { get; set; } // CorporateGUID (length: 50)
        public string CorporateCode { get; set; } // CorporateCode (length: 150)
        public string CorporateName { get; set; } // CorporateName (length: 150)
        public decimal? TotalTax { get; set; } // TotalTax
        public decimal? Month1 { get; set; } // Month1
        public decimal? Month2 { get; set; } // Month2
        public decimal? Month3 { get; set; } // Month3
        public decimal? Month4 { get; set; } // Month4
        public decimal? Month5 { get; set; } // Month5
        public decimal? Month6 { get; set; } // Month6
        public decimal? Month7 { get; set; } // Month7
        public decimal? Month8 { get; set; } // Month8
        public decimal? Month9 { get; set; } // Month9
        public decimal? Month10 { get; set; } // Month10
        public decimal? Month11 { get; set; } // Month11
        public decimal? Month12 { get; set; } // Month12
        public string AttachmentId { get; set; } // AttachmentID (length: 50)
        public int? OrderNum { get; set; } // OrderNum
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string F1 { get; set; } // F1 (length: 2000)
        public string F2 { get; set; } // F2 (length: 2000)
        public string F3 { get; set; } // F3 (length: 2000)
        public int? Year { get; set; } // Year
        public string BudgetTypeId { get; set; } // BudgetTypeID (length: 50)
        public string BudgetTypeCode { get; set; } // BudgetTypeCode (length: 150)
        public string BudgetTypeName { get; set; } // BudgetTypeName (length: 150)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
