// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Invoice
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbInvoice : Entity<Guid>
    {
        public string InvoiceId { get; set; } // InvoiceID (Primary key) (length: 10)
        public string PaymentApplyId { get; set; } // PaymentApplyID (length: 50)
        public string InvoiceCode { get; set; } // InvoiceCode (length: 100)
        public string InvoiceNo { get; set; } // InvoiceNo (length: 100)
        public System.DateTime? BillingDate { get; set; } // BillingDate
        public string PurchaserName { get; set; } // PurchaserName (length: 50)
        public string TaxpayerNo { get; set; } // TaxpayerNo (length: 100)
        public string AddressMobile { get; set; } // AddressMobile (length: 500)
        public string BankAndAccount { get; set; } // BankAndAccount (length: 500)
        public string PwdArea { get; set; } // PwdArea (length: 100)
        public string TotalPriceC { get; set; } // TotalPrice_C (length: 50)
        public decimal? TotalPriceL { get; set; } // TotalPrice_L
        public string SellerName { get; set; } // SellerName (length: 100)
        public string SellerTaxPayerNo { get; set; } // SellerTaxPayerNo (length: 100)
        public string SellerAddressMobile { get; set; } // SellerAddressMobile (length: 500)
        public string SellerBankAndAccount { get; set; } // SellerBankAndAccount (length: 100)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbInvoiceDetails where [TB_InvoiceDetail].[InvoiceID] point to this entity (RefTB_Invoice243)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbInvoiceDetail> TbInvoiceDetails { get; set; } // TB_InvoiceDetail.RefTB_Invoice243

        // Foreign keys

        /// <summary>
        /// Parent TbPaymentApply pointed by [TB_Invoice].([PaymentApplyId]) (RefTB_Payment_Apply242)
        /// </summary>
        public virtual TbPaymentApply TbPaymentApply { get; set; } // RefTB_Payment_Apply242

        public TbInvoice()
        {
            TbInvoiceDetails = new System.Collections.Generic.List<TbInvoiceDetail>();
        }
    }

}
// </auto-generated>
