// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Loan_Apply_ReceivingInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbLoanApplyReceivingInfo : Entity<Guid>
    {
        public string RepaymentId { get; set; } // RepaymentID (Primary key) (length: 50)
        public string LoanId { get; set; } // LoanID (length: 50)
        public decimal? RepaymentMoney { get; set; } // RepaymentMoney
        public System.DateTime? RepaymentTime { get; set; } // RepaymentTime
        public decimal? OffsetMoney { get; set; } // OffsetMoney
        public string Remark { get; set; } // Remark (length: 2000)
        public string ReceivingCompanyId { get; set; } // ReceivingCompanyID (length: 50)
        public string ReceivingCompany { get; set; } // ReceivingCompany (length: 50)
        public string ReceivingBankId { get; set; } // ReceivingBankID (length: 50)
        public string ReceivingBank { get; set; } // ReceivingBank (length: 50)
        public string ReceivingBranchId { get; set; } // ReceivingBranchID (length: 50)
        public string ReceivingBranch { get; set; } // ReceivingBranch (length: 50)
        public string ReceivingAccount { get; set; } // ReceivingAccount (length: 50)
        public string CreatorUserId { get; set; } // CreatorUserID (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string CreatorDeptId { get; set; } // CreatorDeptID (length: 50)
        public string CreatorDeptName { get; set; } // CreatorDeptName (length: 50)
        public System.DateTime? Createdate { get; set; } // Createdate
        public int? Status { get; set; } // Status
        public string ProcInstId { get; set; } // ProcInstID (length: 50)
        public string Latestapprover { get; set; } // Latestapprover (length: 50)
        public string Latestcomment { get; set; } // Latestcomment (length: 1000)
        public System.DateTime? Latestapprovetime { get; set; } // Latestapprovetime

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbRepaymentsDetails where [TB_Repayments_Detail].[RepaymentID] point to this entity (RefTB_Loan_Apply_ReceivingInfo351)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbRepaymentsDetail> TbRepaymentsDetails { get; set; } // TB_Repayments_Detail.RefTB_Loan_Apply_ReceivingInfo351

        // Foreign keys

        /// <summary>
        /// Parent TbLoanApply pointed by [TB_Loan_Apply_ReceivingInfo].([LoanId]) (RefTB_Loan_Apply250)
        /// </summary>
        public virtual TbLoanApply TbLoanApply { get; set; } // RefTB_Loan_Apply250

        public TbLoanApplyReceivingInfo()
        {
            TbRepaymentsDetails = new System.Collections.Generic.List<TbRepaymentsDetail>();
        }
    }

}
// </auto-generated>
