// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Loan_Apply
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbLoanApply : Entity<Guid>
    {
        public string LoanId { get; set; } // LoanID (Primary key) (length: 50)
        public string LoanCode { get; set; } // LoanCode (length: 50)
        public string LoanName { get; set; } // LoanName (length: 50)
        public int? Status { get; set; } // Status
        public int? LoanStatus { get; set; } // LoanStatus
        public string ApplyUserId { get; set; } // ApplyUserID (length: 50)
        public string ApplyUserName { get; set; } // ApplyUserName (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockName { get; set; } // BlockName (length: 50)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string CostCenterName { get; set; } // CostCenterName (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public string ProjectId { get; set; } // ProjectID (length: 50)
        public string ProjectName { get; set; } // ProjectName (length: 50)
        public string PayCorporateId { get; set; } // PayCorporateID (length: 50)
        public string PayCorporateName { get; set; } // PayCorporateName (length: 50)
        public string PlanApplyId { get; set; } // PlanApplyID (length: 50)
        public decimal? LoanAmount { get; set; } // LoanAmount
        public decimal? NoSettledAmount { get; set; } // NoSettledAmount
        public System.DateTime? RepaymentTime { get; set; } // RepaymentTime
        public string Remark { get; set; } // Remark (length: 2000)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string ReceivingName { get; set; } // ReceivingName (length: 50)
        public string ReceivingBank { get; set; } // ReceivingBank (length: 50)
        public string ReceivingBranch { get; set; } // ReceivingBranch (length: 50)
        public string ReceivingAccount { get; set; } // ReceivingAccount (length: 50)
        public string CreatorUserId { get; set; } // CreatorUserID (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string CreatorDeptId { get; set; } // CreatorDeptID (length: 50)
        public string CreatorDeptName { get; set; } // CreatorDeptName (length: 50)
        public string ProcInstId { get; set; } // ProcInstID (length: 50)
        public string LatestApprover { get; set; } // LatestApprover (length: 50)
        public string LatestComment { get; set; } // LatestComment (length: 1000)
        public System.DateTime? LatestApproveTime { get; set; } // LatestApproveTime
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string BelongId { get; set; } // BelongID (length: 50)
        public string BelongName { get; set; } // BelongName (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbLoanApplyReceivingInfoes where [TB_Loan_Apply_ReceivingInfo].[LoanID] point to this entity (RefTB_Loan_Apply250)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbLoanApplyReceivingInfo> TbLoanApplyReceivingInfoes { get; set; } // TB_Loan_Apply_ReceivingInfo.RefTB_Loan_Apply250

        public TbLoanApply()
        {
            TbLoanApplyReceivingInfoes = new System.Collections.Generic.List<TbLoanApplyReceivingInfo>();
        }
    }

}
// </auto-generated>
