// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Monthly_PayPlan_BudgetItems
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbMonthlyPayPlanBudgetItem1 : Entity<Guid>
    {
        public string PayPlanBudgetItemId { get; set; } // PayPlanBudgetItemID (Primary key) (length: 50)
        public string PayPlanCostCenterId { get; set; } // PayPlanCostCenterID (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string UpperBudgetItemId { get; set; } // UpperBudgetItemID (length: 50)
        public string UpperBudgetItemName { get; set; } // UpperBudgetItemName (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string ContractName { get; set; } // ContractName (length: 50)
        public decimal? PlanPayAmount { get; set; } // PlanPayAmount
        public decimal? BudgetItemContractAmount { get; set; } // BudgetItemContractAmount
        public decimal? PendingPayAmount { get; set; } // PendingPayAmount
        public System.DateTime? PlanPayDate { get; set; } // PlanPayDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbMonthlyPayPlanBudgetItem pointed by [TB_Monthly_PayPlan_BudgetItems].([BudgetItemId]) (RefTB_Monthly_PayPlan_Budget_Item115)
        /// </summary>
        public virtual TbMonthlyPayPlanBudgetItem TbMonthlyPayPlanBudgetItem { get; set; } // RefTB_Monthly_PayPlan_Budget_Item115

        /// <summary>
        /// Parent TbMonthlyPayPlanCostCenter pointed by [TB_Monthly_PayPlan_BudgetItems].([PayPlanCostCenterId]) (RefTB_Monthly_PayPlan_CostCenter68)
        /// </summary>
        public virtual TbMonthlyPayPlanCostCenter TbMonthlyPayPlanCostCenter { get; set; } // RefTB_Monthly_PayPlan_CostCenter68
    }

}
// </auto-generated>
