// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_OperationRecord
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbOperationRecord : Entity<Guid>
    {
        public string RecordId { get; set; } // RecordID (Primary key) (length: 50)
        public string UserId { get; set; } // UserID (length: 50)
        public System.DateTime? AppoveTimeBx { get; set; } // AppoveTime_BX
        public System.DateTime? PaidTimeBx { get; set; } // PaidTime_BX
        public System.DateTime? AppoveTimeHt { get; set; } // AppoveTime_HT
        public System.DateTime? AppoveTimeFk { get; set; } // AppoveTime_FK
        public System.DateTime? PaidTimeFk { get; set; } // PaidTime_FK
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
