// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_OrganizationUnit_bak
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbOrganizationUnitBak : Entity<Guid>
    {
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (Primary key) (length: 50)
        public string OrgUnitName { get; set; } // OrgUnitName (length: 50)
        public string UpperOrgUnitGuid { get; set; } // UpperOrgUnitGUID (length: 50)
        public string OrgUnitType { get; set; } // OrgUnitType (length: 50)
        public string OrgUnitLever { get; set; } // OrgUnitLever (length: 50)
        public int? OrderIndex { get; set; } // OrderIndex
        public string BelongDutyLine { get; set; } // BelongDutyLine (length: 50)
        public int? IsCostCenter { get; set; } // IsCostCenter
        public int? IsInvalid { get; set; } // IsInvalid
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
