// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Org_User_Relate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbOrgUserRelate : Entity<Guid>
    {
        public string RelateId { get; set; } // RelateID (Primary key) (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public string UserId { get; set; } // UserID (length: 50)
        public int? IsMain { get; set; } // IsMain

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbOrganizationUnit pointed by [TB_Org_User_Relate].([OrgUnitGuid]) (RefTB_OrganizationUnit4)
        /// </summary>
        public virtual TbOrganizationUnit TbOrganizationUnit { get; set; } // RefTB_OrganizationUnit4

        /// <summary>
        /// Parent TbUser pointed by [TB_Org_User_Relate].([UserId]) (RefTB_User5)
        /// </summary>
        public virtual TbUser TbUser { get; set; } // RefTB_User5
    }

}
// </auto-generated>
