// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Payment_Apply_ReceivingInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbPaymentApplyReceivingInfo : Entity<Guid>
    {
        public string ReceivingId { get; set; } // ReceivingID (Primary key) (length: 50)
        public string PaymentApplyId { get; set; } // PaymentApplyID (length: 50)
        public string ReceivingCompanyId { get; set; } // ReceivingCompanyID (length: 50)
        public string ReceivingCompany { get; set; } // ReceivingCompany (length: 200)
        public string ReceivingBank { get; set; } // ReceivingBank (length: 50)
        public string ReceivingAccount { get; set; } // ReceivingAccount (length: 100)
        public string OrgUnitGuid { get; set; } // OrgUnitGuid (length: 50)
        public string OrgUnitName { get; set; } // OrgUnitName (length: 50)
        public decimal? ApplyAmount { get; set; } // ApplyAmount
        public string ReceivingBankId { get; set; } // ReceivingBankID (length: 50)
        public string ReceivingSubBank { get; set; } // ReceivingSubBank (length: 50)
        public string ReceivingSubBankId { get; set; } // ReceivingSubBankID (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
