// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Payment_Apply_Restaurant
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbPaymentApplyRestaurant : Entity<Guid>
    {
        public string RestaurantId { get; set; } // RestaurantID (Primary key) (length: 50)
        public string PaymentApplyId { get; set; } // PaymentApplyID (length: 50)
        public string TravelPersonnel { get; set; } // TravelPersonnel (length: 50)
        public string Position { get; set; } // Position (length: 50)
        public System.DateTime? DateFrom { get; set; } // DateFrom
        public System.DateTime? DateEnd { get; set; } // DateEnd
        public string Address { get; set; } // Address (length: 500)
        public decimal? StandardCost { get; set; } // StandardCost
        public decimal? Days { get; set; } // Days
        public int? PersionNumber { get; set; } // PersionNumber
        public decimal? ReceptionNumber { get; set; } // ReceptionNumber
        public decimal? CutNumber { get; set; } // CutNumber
        public decimal? BoardNumber { get; set; } // BoardNumber
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public decimal? LunchAllowance { get; set; } // LunchAllowance

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
