// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Payment_Apply
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbPaymentApply : Entity<Guid>
    {
        public string PaymentApplyId { get; set; } // PaymentApplyID (Primary key) (length: 50)
        public string PaymentApplyCode { get; set; } // PaymentApplyCode (length: 50)
        public string PaymentSubject { get; set; } // PaymentSubject (length: 100)
        public string PaymentWay { get; set; } // PaymentWay (length: 50)
        public string PaymentWayName { get; set; } // PaymentWayName (length: 50)
        public string PlanApplyId { get; set; } // PlanApplyID (length: 50)
        public string PaymentType { get; set; } // PaymentType (length: 50)
        public int? Status { get; set; } // Status
        public int? PayStatus { get; set; } // PayStatus
        public System.DateTime? PayTime { get; set; } // PayTime
        public int? IsWarrantyGold { get; set; } // IsWarrantyGold
        public decimal? CurrentApplyAmount { get; set; } // CurrentApplyAmount
        public decimal? NoTaxAmount { get; set; } // NoTaxAmount
        public decimal? TotalTaxAmount { get; set; } // TotalTaxAmount
        public decimal? PaidAmountForApply { get; set; } // PaidAmountForApply
        public decimal? WaitingPayAmount { get; set; } // WaitingPayAmount
        public string CorporateGuid { get; set; } // CorporateGUID (length: 50)
        public string CorporateName { get; set; } // CorporateName (length: 50)
        public string PaymentDesc { get; set; } // PaymentDesc (length: 1000)
        public string ProcInstId { get; set; } // ProcInstID (length: 50)
        public string LatestApprover { get; set; } // LatestApprover (length: 50)
        public string LatestComment { get; set; } // LatestComment (length: 1000)
        public System.DateTime? LatestApproveTime { get; set; } // LatestApproveTime
        public string SubmitUser { get; set; } // SubmitUser (length: 50)
        public string SubmitUserLoginId { get; set; } // SubmitUserLoginID (length: 50)
        public string SubmitUserName { get; set; } // SubmitUserName (length: 50)
        public string SubmitUserDeptId { get; set; } // SubmitUserDeptID (length: 50)
        public string SubmitUserDeptName { get; set; } // SubmitUserDeptName (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGuid (length: 50)
        public string OrgUnitName { get; set; } // OrgUnitName (length: 50)
        public string Creator { get; set; } // Creator (length: 50)
        public string CreatorLoginId { get; set; } // CreatorLoginID (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string CreatorDeptId { get; set; } // CreatorDeptID (length: 50)
        public string CreatorDeptName { get; set; } // CreatorDeptName (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public string UpdateUserName { get; set; } // UpdateUserName (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 100)
        public string F2 { get; set; } // F2 (length: 100)
        public string F3 { get; set; } // F3 (length: 100)
        public int? JoinCount { get; set; } // JoinCount
        public decimal? AvgCost { get; set; } // AvgCost
        public string ReceivingName { get; set; } // ReceivingName (length: 50)
        public string ReceivingBank { get; set; } // ReceivingBank (length: 50)
        public string ReceivingBranch { get; set; } // ReceivingBranch (length: 50)
        public string ReceivingAccount { get; set; } // ReceivingAccount (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string BlockName { get; set; } // BlockName (length: 50)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string CostCenterName { get; set; } // CostCenterName (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public string ProjectId { get; set; } // ProjectID (length: 50)
        public string ProjectName { get; set; } // ProjectName (length: 50)
        public System.DateTime? PayFinishTime { get; set; } // PayFinishTime
        public string SpecialRemark { get; set; } // SpecialRemark (length: 1000)
        public decimal? WarrantyGoldTaxAmount { get; set; } // WarrantyGoldTaxAmount
        public System.DateTime? WarrantyGoldPayTime { get; set; } // WarrantyGoldPayTime

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbInvoices where [TB_Invoice].[PaymentApplyID] point to this entity (RefTB_Payment_Apply242)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbInvoice> TbInvoices { get; set; } // TB_Invoice.RefTB_Payment_Apply242
        /// <summary>
        /// Child TbPaymentApplyDetails where [TB_Payment_Apply_Detail].[PaymentApplyID] point to this entity (RefTB_Payment_Apply288)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbPaymentApplyDetail> TbPaymentApplyDetails { get; set; } // TB_Payment_Apply_Detail.RefTB_Payment_Apply288
        /// <summary>
        /// Child TbPaymentOthers where [TB_Payment_Other].[PaymentApplyID] point to this entity (RefTB_Payment_Apply248)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbPaymentOther> TbPaymentOthers { get; set; } // TB_Payment_Other.RefTB_Payment_Apply248
        /// <summary>
        /// Child TbPaymentStays where [TB_Payment_Stay].[PaymentApplyID] point to this entity (RefTB_Payment_Apply246)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbPaymentStay> TbPaymentStays { get; set; } // TB_Payment_Stay.RefTB_Payment_Apply246
        /// <summary>
        /// Child TbPaymentTraffics where [TB_Payment_Traffic].[PaymentApplyID] point to this entity (RefTB_Payment_Apply247)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbPaymentTraffic> TbPaymentTraffics { get; set; } // TB_Payment_Traffic.RefTB_Payment_Apply247
        /// <summary>
        /// Child TbSpareMoneyRepaymentsDetails where [TB_SpareMoneyRepayments_Detail].[PaymentApplyID] point to this entity (RefTB_Payment_Apply351)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbSpareMoneyRepaymentsDetail> TbSpareMoneyRepaymentsDetails { get; set; } // TB_SpareMoneyRepayments_Detail.RefTB_Payment_Apply351

        public TbPaymentApply()
        {
            TbInvoices = new System.Collections.Generic.List<TbInvoice>();
            TbPaymentApplyDetails = new System.Collections.Generic.List<TbPaymentApplyDetail>();
            TbPaymentOthers = new System.Collections.Generic.List<TbPaymentOther>();
            TbPaymentStays = new System.Collections.Generic.List<TbPaymentStay>();
            TbPaymentTraffics = new System.Collections.Generic.List<TbPaymentTraffic>();
            TbSpareMoneyRepaymentsDetails = new System.Collections.Generic.List<TbSpareMoneyRepaymentsDetail>();
        }
    }

}
// </auto-generated>
