// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Payment_Stay
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbPaymentStay : Entity<Guid>
    {
        public string StayId { get; set; } // StayID (Primary key) (length: 50)
        public string PaymentApplyId { get; set; } // PaymentApplyID (length: 50)
        public int? Sort { get; set; } // Sort
        public string HotelName { get; set; } // HotelName (length: 200)
        public int? Days { get; set; } // Days
        public string Level { get; set; } // Level (length: 50)
        public string LevelName { get; set; } // LevelName (length: 50)
        public decimal? TotalPrice { get; set; } // TotalPrice
        public decimal? Subtotal { get; set; } // Subtotal
        public string ExcessiveDesc { get; set; } // ExcessiveDesc (length: 200)
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbPaymentApply pointed by [TB_Payment_Stay].([PaymentApplyId]) (RefTB_Payment_Apply246)
        /// </summary>
        public virtual TbPaymentApply TbPaymentApply { get; set; } // RefTB_Payment_Apply246
    }

}
// </auto-generated>
