// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Payment_Apply_Detail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbPaymentApplyDetail : Entity<Guid>
    {
        public string PaymentApplyDetailId { get; set; } // PaymentApplyDetailID (Primary key) (length: 50)
        public string PaymentApplyId { get; set; } // PaymentApplyID (length: 50)
        public string ExecutionDetailId { get; set; } // ExecutionDetailID (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public decimal? AvailableBudget { get; set; } // AvailableBudget
        public decimal? TotalTaxAmount { get; set; } // TotalTaxAmount
        public decimal? TaxRate { get; set; } // TaxRate
        public decimal? TaxAmount { get; set; } // TaxAmount
        public decimal? NoTaxAmount { get; set; } // NoTaxAmount
        public string ReceiptType { get; set; } // ReceiptType (length: 50)
        public string ReceiptTypeName { get; set; } // ReceiptTypeName (length: 50)
        public decimal? ThisApplyPaymentAmount { get; set; } // ThisApplyPaymentAmount
        public decimal? ThisApplyPayTaxAmount { get; set; } // ThisApplyPayTaxAmount
        public string Remark { get; set; } // Remark (length: 2147483647)
        public decimal? PaidAmount { get; set; } // PaidAmount
        public decimal? ApprovedNoPaidAmount { get; set; } // ApprovedNoPaidAmount
        public decimal? ApprovingApplyAmount { get; set; } // ApprovingApplyAmount
        public decimal? BudgetAmount { get; set; } // BudgetAmount
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string PlanApplyDetailId { get; set; } // PlanApplyDetailID (length: 50)
        public System.DateTime? BudgetRangeStart { get; set; } // BudgetRangeStart
        public System.DateTime? BudgetRangeEnd { get; set; } // BudgetRangeEnd
        public decimal? OffsetAmount { get; set; } // OffsetAmount
        public string BillingCompanyId { get; set; } // BillingCompanyID (length: 50)
        public string BillingcompanyName { get; set; } // BillingcompanyName (length: 50)
        public string BelongId { get; set; } // BelongID (length: 50)
        public string BelongName { get; set; } // BelongName (length: 50)
        public int? JoinCount { get; set; } // JoinCount
        public decimal? AvgCost { get; set; } // AvgCost

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbPaymentApply pointed by [TB_Payment_Apply_Detail].([PaymentApplyId]) (RefTB_Payment_Apply288)
        /// </summary>
        public virtual TbPaymentApply TbPaymentApply { get; set; } // RefTB_Payment_Apply288
    }

}
// </auto-generated>
