// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Plan_Apply
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbPlanApply : Entity<Guid>
    {
        public string PlanApplyId { get; set; } // PlanApplyID (Primary key) (length: 50)
        public string MainApplyKeyWord { get; set; } // MainApplyKeyWord (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string PlanApplyCode { get; set; } // PlanApplyCode (length: 50)
        public string PlanApplyName { get; set; } // PlanApplyName (length: 100)
        public string EventId { get; set; } // EventID (length: 50)
        public decimal? TotalAmount { get; set; } // TotalAmount
        public System.DateTime? StartDate { get; set; } // StartDate
        public System.DateTime? EndDate { get; set; } // EndDate
        public string ProjectIntroduction { get; set; } // ProjectIntroduction (length: 2000)
        public string Creator { get; set; } // Creator (length: 50)
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public string CreateDepartment { get; set; } // CreateDepartment (length: 50)
        public string DepartmentName { get; set; } // DepartmentName (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string Modifier { get; set; } // Modifier (length: 50)
        public string ModiftyName { get; set; } // ModiftyName (length: 50)
        public System.DateTime? ModiftyDate { get; set; } // ModiftyDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string BudgetTypeId { get; set; } // BudgetTypeID (length: 50)
        public bool? IsExtraBudget { get; set; } // IsExtraBudget
        public int? Status { get; set; } // Status
        public string ProcInstId { get; set; } // ProcInstID (length: 50)
        public string LatestApprover { get; set; } // LatestApprover (length: 50)
        public string LatestComment { get; set; } // LatestComment (length: 50)
        public System.DateTime? LatestApproveTime { get; set; } // LatestApproveTime
        public bool? IsYearBudget { get; set; } // IsYearBudget

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbPlanApplyDetails where [TB_Plan_Apply_Detail].[PlanApplyID] point to this entity (RefTB_Plan_Apply314)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbPlanApplyDetail> TbPlanApplyDetails { get; set; } // TB_Plan_Apply_Detail.RefTB_Plan_Apply314

        // Foreign keys

        /// <summary>
        /// Parent TbBlock pointed by [TB_Plan_Apply].([BlockId]) (RefTB_Block238)
        /// </summary>
        public virtual TbBlock TbBlock { get; set; } // RefTB_Block238

        /// <summary>
        /// Parent TbBudgetItem pointed by [TB_Plan_Apply].([BudgetItemId]) (RefTB_Budget_Item237)
        /// </summary>
        public virtual TbBudgetItem TbBudgetItem { get; set; } // RefTB_Budget_Item237

        /// <summary>
        /// Parent TbCostCenter pointed by [TB_Plan_Apply].([CostCenterId]) (RefTB_CostCenter239)
        /// </summary>
        public virtual TbCostCenter TbCostCenter { get; set; } // RefTB_CostCenter239

        public TbPlanApply()
        {
            TbPlanApplyDetails = new System.Collections.Generic.List<TbPlanApplyDetail>();
        }
    }

}
// </auto-generated>
