// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Plan_Apply_Detail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbPlanApplyDetail : Entity<Guid>
    {
        public string PlanApplyDetailId { get; set; } // PlanApplyDetailID (Primary key) (length: 50)
        public string MainPlanApplyDetailId { get; set; } // MainPlanApplyDetailID (length: 50)
        public string PlanApplyId { get; set; } // PlanApplyID (length: 50)
        public string BelongId { get; set; } // BelongID (length: 50)
        public string TransactionDetails { get; set; } // TransactionDetails (length: 500)
        public string YearId { get; set; } // YearID (length: 50)
        public System.DateTime? StartDate { get; set; } // StartDate
        public System.DateTime? EndDate { get; set; } // EndDate
        public decimal? TransactionAmount { get; set; } // TransactionAmount
        public string Remark { get; set; } // Remark (length: 1000)
        public string PayWay { get; set; } // PayWay (length: 50)
        public string BillingCompany { get; set; } // BillingCompany (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string BelongName { get; set; } // BelongName (length: 50)
        public string BillingcompanyName { get; set; } // BillingcompanyName (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbPlanApply pointed by [TB_Plan_Apply_Detail].([PlanApplyId]) (RefTB_Plan_Apply314)
        /// </summary>
        public virtual TbPlanApply TbPlanApply { get; set; } // RefTB_Plan_Apply314

        /// <summary>
        /// Parent TbYear pointed by [TB_Plan_Apply_Detail].([YearId]) (RefTB_Year324)
        /// </summary>
        public virtual TbYear TbYear { get; set; } // RefTB_Year324
    }

}
// </auto-generated>
