// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Progress_Sheet
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbProgressSheet : Entity<Guid>
    {
        public string ProgressSheetId { get; set; } // ProgressSheetId (Primary key) (length: 50)
        public string ContractId { get; set; } // ContractId (length: 50)
        public int? Year { get; set; } // Year
        public string ContractName { get; set; } // ContractName (length: 100)
        public double? Month1 { get; set; } // Month1
        public double? Month2 { get; set; } // Month2
        public double? Month3 { get; set; } // Month3
        public double? Month4 { get; set; } // Month4
        public double? Month5 { get; set; } // Month5
        public double? Month6 { get; set; } // Month6
        public double? Month7 { get; set; } // Month7
        public double? Month8 { get; set; } // Month8
        public double? Month9 { get; set; } // Month9
        public double? Month10 { get; set; } // Month10
        public double? Month11 { get; set; } // Month11
        public double? Month12 { get; set; } // Month12
        public string Remark { get; set; } // Remark (length: 500)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbProgressOutputValues where [TB_ProgressOutputValue].[ProgressSheetId] point to this entity (RefTB_Progress_Sheet3521)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbProgressOutputValue> TbProgressOutputValues { get; set; } // TB_ProgressOutputValue.RefTB_Progress_Sheet3521

        public TbProgressSheet()
        {
            TbProgressOutputValues = new System.Collections.Generic.List<TbProgressOutputValue>();
        }
    }

}
// </auto-generated>
