// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Reimbursement_Standard
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbReimbursementStandard : Entity<Guid>
    {
        public string ReimbursementStandardId { get; set; } // ReimbursementStandardID (Primary key) (length: 50)
        public string RankId { get; set; } // RankID (length: 50)
        public string RankCode { get; set; } // RankCode (length: 50)
        public string RankName { get; set; } // RankName (length: 50)
        public string TravelAreaId { get; set; } // TravelAreaID (length: 50)
        public string TravelAreaCode { get; set; } // TravelAreaCode (length: 50)
        public string TravelAreaName { get; set; } // TravelAreaName (length: 50)
        public string ProjectId { get; set; } // ProjectID (length: 50)
        public string ProjectCode { get; set; } // ProjectCode (length: 50)
        public string ProjectName { get; set; } // ProjectName (length: 50)
        public decimal? ControlStandards { get; set; } // ControlStandards
        public string F1 { get; set; } // F1 (length: 100)
        public string F2 { get; set; } // F2 (length: 100)
        public string F3 { get; set; } // F3 (length: 100)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
