// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Repayments_Detail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbRepaymentsDetail : Entity<Guid>
    {
        public string RepaymentDetailId { get; set; } // RepaymentDetailId (Primary key) (length: 50)
        public string RepaymentCode { get; set; } // RepaymentCode (length: 50)
        public decimal? Amount { get; set; } // Amount
        public string Remark { get; set; } // Remark (length: 200)
        public string CostCenterId { get; set; } // CostCenterID (length: 50)
        public string CostCenterName { get; set; } // CostCenterName (length: 50)
        public string BelongId { get; set; } // BelongID (length: 50)
        public string BelongName { get; set; } // BelongName (length: 50)
        public string BudgetItemName { get; set; } // BudgetItemName (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 50)
        public string RepaymentId { get; set; } // RepaymentID (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbLoanApplyReceivingInfo pointed by [TB_Repayments_Detail].([RepaymentId]) (RefTB_Loan_Apply_ReceivingInfo351)
        /// </summary>
        public virtual TbLoanApplyReceivingInfo TbLoanApplyReceivingInfo { get; set; } // RefTB_Loan_Apply_ReceivingInfo351
    }

}
// </auto-generated>
