// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Remind_Queue
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbRemindQueue : Entity<Guid>
    {
        public string RemindQueueId { get; set; } // RemindQueueID (Primary key) (length: 50)
        public string ContentKey { get; set; } // ContentKey (length: 50)
        public string Type { get; set; } // Type (length: 20)
        public int? AlreadyRate { get; set; } // AlreadyRate
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string CreateUser { get; set; } // CreateUser (length: 50)
        public string UpdateUserName { get; set; } // UpdateUserName (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public string CreateUserName { get; set; } // CreateUserName (length: 50)
        public string UpdateUser { get; set; } // UpdateUser (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbRemindContents where [TB_Remind_Content].[RemindQueueID] point to this entity (RefTB_Remind_Queue350)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbRemindContent> TbRemindContents { get; set; } // TB_Remind_Content.RefTB_Remind_Queue350

        public TbRemindQueue()
        {
            TbRemindContents = new System.Collections.Generic.List<TbRemindContent>();
        }
    }

}
// </auto-generated>
