// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_ServiceOrders
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbServiceOrder : Entity<Guid>
    {
        public string OrderId { get; set; } // OrderID (Primary key) (length: 50)
        public string BlockId { get; set; } // BlockID (length: 50)
        public string SupplierId { get; set; } // SupplierID (length: 50)
        public string PlanApplyId { get; set; } // PlanApplyID (length: 50)
        public string PlanApplyName { get; set; } // PlanApplyName (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string ContractName { get; set; } // ContractName (length: 50)
        public string BudgetItemId { get; set; } // BudgetItemID (length: 10)
        public string CostCenterId { get; set; } // CostCenterID (length: 10)
        public string CreatorDeptId { get; set; } // CreatorDeptID (length: 50)
        public string CreatorDeptName { get; set; } // CreatorDeptName (length: 100)
        public bool? IsSeeAmount { get; set; } // IsSeeAmount
        public string Summary { get; set; } // Summary (length: 2147483647)
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbServiceOrderDetails where [TB_ServiceOrder_Detail].[OrderID] point to this entity (RefTB_ServiceOrders234)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbServiceOrderDetail> TbServiceOrderDetails { get; set; } // TB_ServiceOrder_Detail.RefTB_ServiceOrders234

        public TbServiceOrder()
        {
            TbServiceOrderDetails = new System.Collections.Generic.List<TbServiceOrderDetail>();
        }
    }

}
// </auto-generated>
