// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_ServiceOrder_Detail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbServiceOrderDetail : Entity<Guid>
    {
        public string OrderDetailId { get; set; } // OrderDetailID (Primary key) (length: 50)
        public string OrderId { get; set; } // OrderID (length: 50)
        public System.DateTime? ServiceDate { get; set; } // ServiceDate
        public string ServiceMatters { get; set; } // ServiceMatters (length: 200)
        public decimal? ContractAmount { get; set; } // ContractAmount
        public decimal? TotalConfirmAmount { get; set; } // TotalConfirmAmount
        public decimal? ThisConfirmAmount { get; set; } // ThisConfirmAmount
        public string Remark { get; set; } // Remark (length: 200)
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbServiceOrder pointed by [TB_ServiceOrder_Detail].([OrderId]) (RefTB_ServiceOrders234)
        /// </summary>
        public virtual TbServiceOrder TbServiceOrder { get; set; } // RefTB_ServiceOrders234
    }

}
// </auto-generated>
