// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_StandardContractContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbStandardContractContent : Entity<Guid>
    {
        public string ContentId { get; set; } // ContentID (Primary key) (length: 50)
        public string ContractTemplateId { get; set; } // ContractTemplateID (length: 50)
        public int? OrderIndex { get; set; } // OrderIndex
        public int? PageIndex { get; set; } // PageIndex
        public string ParagraphContent { get; set; } // ParagraphContent (length: 1073741823)
        public int? IsEdit { get; set; } // IsEdit
        public int? IsMainPoints { get; set; } // IsMainPoints
        public int? IsNeedAttach { get; set; } // IsNeedAttach
        public string F1 { get; set; } // F1 (length: 200)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 2000)
        public int? IsLvyue { get; set; } // IsLvyue
        public string LvyueTableName { get; set; } // LvyueTableName (length: 50)
        public int? Vision { get; set; } // Vision

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbContractTemplate pointed by [TB_StandardContractContent].([ContractTemplateId]) (RefTB_Contract_Template171)
        /// </summary>
        public virtual TbContractTemplate TbContractTemplate { get; set; } // RefTB_Contract_Template171
    }

}
// </auto-generated>
