// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Supplier_CooperationRecord
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbSupplierCooperationRecord : Entity<Guid>
    {
        public string CooperationRecordId { get; set; } // CooperationRecordID (Primary key) (length: 50)
        public string SupplierId { get; set; } // SupplierID (length: 50)
        public string ProjectId { get; set; } // ProjectID (length: 50)
        public string ContractId { get; set; } // ContractID (length: 50)
        public string CreatorLoginId { get; set; } // CreatorLoginID (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string Score { get; set; } // Score (length: 50)
        public decimal? AvgScore { get; set; } // AvgScore
        public decimal? LowScore { get; set; } // LowScore
        public string Content { get; set; } // Content (length: 200)
        public System.DateTime? CreateDate { get; set; } // CreateDate

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbSupplierAssesses where [TB_Supplier_Assess].[CooperationRecordID] point to this entity (RefTB_Supplier_CooperationRecord236)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbSupplierAssess> TbSupplierAssesses { get; set; } // TB_Supplier_Assess.RefTB_Supplier_CooperationRecord236

        // Foreign keys

        /// <summary>
        /// Parent TbSupplierBasic pointed by [TB_Supplier_CooperationRecord].([SupplierId]) (RefTB_Supplier_Basic231)
        /// </summary>
        public virtual TbSupplierBasic TbSupplierBasic { get; set; } // RefTB_Supplier_Basic231

        public TbSupplierCooperationRecord()
        {
            TbSupplierAssesses = new System.Collections.Generic.List<TbSupplierAssess>();
        }
    }

}
// </auto-generated>
