// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Sub_Budget_lItem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbSubBudgetLItem : Entity<Guid>
    {
        public string SubBudgetItemId { get; set; } // SubBudgetItemID (Primary key) (length: 50)
        public string BudgetSubTypeId { get; set; } // BudgetSubTypeID (length: 50)
        public string BudgettemCode { get; set; } // BudgettemCode (length: 20)
        public string BudgetlItemName { get; set; } // BudgetlItemName (length: 4000)
        public string Describe { get; set; } // Describe (length: 1000)
        public int? OrderIndex { get; set; } // OrderIndex
        public int? Status { get; set; } // Status
        public string Creator { get; set; } // Creator (length: 20)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 20)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)
        public int? IsNeedContract { get; set; } // IsNeedContract
        public int? IsNeedPay { get; set; } // IsNeedPay

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
