// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Supplier_Assess
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbSupplierAssess : Entity<Guid>
    {
        public string AssessId { get; set; } // AssessID (Primary key) (length: 50)
        public string CooperationRecordId { get; set; } // CooperationRecordID (length: 50)
        public string Score { get; set; } // Score (length: 50)
        public decimal? IntegratedScore { get; set; } // IntegratedScore
        public int? ServiceAttitude { get; set; } // ServiceAttitude
        public int? OnTimeDelivery { get; set; } // OnTimeDelivery
        public int? ReasonablePrice { get; set; } // ReasonablePrice
        public int? Quality { get; set; } // Quality
        public string Content { get; set; } // Content (length: 200)
        public string SupplierId { get; set; } // SupplierID (length: 50)
        public string SupplierName { get; set; } // SupplierName (length: 100)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string CreateUser { get; set; } // CreateUser (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbSupplierCooperationRecord pointed by [TB_Supplier_Assess].([CooperationRecordId]) (RefTB_Supplier_CooperationRecord236)
        /// </summary>
        public virtual TbSupplierCooperationRecord TbSupplierCooperationRecord { get; set; } // RefTB_Supplier_CooperationRecord236
    }

}
// </auto-generated>
