// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Supplier_Contact
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbSupplierContact : Entity<Guid>
    {
        public string SupplierContactId { get; set; } // SupplierContactID (Primary key) (length: 50)
        public string SupplierId { get; set; } // SupplierID (length: 50)
        public string City { get; set; } // City (length: 50)
        public string CityName { get; set; } // CityName (length: 50)
        public string Address { get; set; } // Address (length: 200)
        public string ContactName { get; set; } // ContactName (length: 50)
        public string Mobile { get; set; } // Mobile (length: 50)
        public string Tel { get; set; } // Tel (length: 50)
        public string Email { get; set; } // Email (length: 50)
        public string Remark { get; set; } // Remark (length: 200)
        public System.DateTime? CreateDate { get; set; } // CreateDate

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbSupplierBasic pointed by [TB_Supplier_Contact].([SupplierId]) (RefTB_Supplier_Basic227)
        /// </summary>
        public virtual TbSupplierBasic TbSupplierBasic { get; set; } // RefTB_Supplier_Basic227
    }

}
// </auto-generated>
