// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Supplier_Basic
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbSupplierBasic : Entity<Guid>
    {
        public string SupplierId { get; set; } // SupplierID (Primary key) (length: 50)
        public string SupplierNo { get; set; } // SupplierNo (length: 50)
        public string CompanyName { get; set; } // CompanyName (length: 100)
        public string CompanyEnName { get; set; } // CompanyEnName (length: 50)
        public string LegalRepresen { get; set; } // LegalRepresen (length: 50)
        public string CompanyType { get; set; } // CompanyType (length: 50)
        public string SocialCreditCode { get; set; } // SocialCreditCode (length: 50)
        public string LicenseNo { get; set; } // LicenseNo (length: 50)
        public string TaxRegisterNo { get; set; } // TaxRegisterNo (length: 50)
        public string OrgNo { get; set; } // OrgNo (length: 50)
        public string OrgUnitGuid { get; set; } // OrgUnitGUID (length: 50)
        public string OrgUnitName { get; set; } // OrgUnitName (length: 100)
        public string TaxRate { get; set; } // TaxRate (length: 50)
        public string SupplierCategory { get; set; } // SupplierCategory (length: 200)
        public string Status { get; set; } // Status (length: 20)
        public string Label { get; set; } // Label (length: 50)
        public string Creator { get; set; } // Creator (length: 50)
        public string CreatorName { get; set; } // CreatorName (length: 50)
        public string CreatorDeptId { get; set; } // CreatorDeptID (length: 50)
        public string CreatorDeptName { get; set; } // CreatorDeptName (length: 50)
        public System.DateTime? ModifyDate { get; set; } // ModifyDate
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string Procinstid { get; set; } // Procinstid (length: 50)
        public string F1 { get; set; } // F1 (length: 200)
        public string F2 { get; set; } // F2 (length: 200)
        public System.DateTime? StartDate { get; set; } // StartDate
        public System.DateTime? EndDate { get; set; } // EndDate
        public string ApproveStatus { get; set; } // ApproveStatus (length: 20)
        public string ModifyId { get; set; } // ModifyId (length: 50)
        public string ModifyName { get; set; } // ModifyName (length: 50)
        public string ModifyOrgUnitGuid { get; set; } // ModifyOrgUnitGuid (length: 50)
        public string ModifyOrgUnitName { get; set; } // ModifyOrgUnitName (length: 50)
        public string OriginalSupplierNo { get; set; } // OriginalSupplierNo (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child TbSupplierBanks where [TB_Supplier_Bank].[SupplierID] point to this entity (RefTB_Supplier_Basic228)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbSupplierBank> TbSupplierBanks { get; set; } // TB_Supplier_Bank.RefTB_Supplier_Basic228
        /// <summary>
        /// Child TbSupplierCategories where [TB_Supplier_Category].[SupplierID] point to this entity (RefTB_Supplier_Basic252)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbSupplierCategory> TbSupplierCategories { get; set; } // TB_Supplier_Category.RefTB_Supplier_Basic252
        /// <summary>
        /// Child TbSupplierContacts where [TB_Supplier_Contact].[SupplierID] point to this entity (RefTB_Supplier_Basic227)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbSupplierContact> TbSupplierContacts { get; set; } // TB_Supplier_Contact.RefTB_Supplier_Basic227
        /// <summary>
        /// Child TbSupplierCooperationRecords where [TB_Supplier_CooperationRecord].[SupplierID] point to this entity (RefTB_Supplier_Basic231)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbSupplierCooperationRecord> TbSupplierCooperationRecords { get; set; } // TB_Supplier_CooperationRecord.RefTB_Supplier_Basic231

        public TbSupplierBasic()
        {
            TbSupplierBanks = new System.Collections.Generic.List<TbSupplierBank>();
            TbSupplierCategories = new System.Collections.Generic.List<TbSupplierCategory>();
            TbSupplierContacts = new System.Collections.Generic.List<TbSupplierContact>();
            TbSupplierCooperationRecords = new System.Collections.Generic.List<TbSupplierCooperationRecord>();
        }
    }

}
// </auto-generated>
