// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_Template_Budget_Relate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbTemplateBudgetRelate : Entity<Guid>
    {
        public string RelateId { get; set; } // RelateID (Primary key) (length: 50)
        public string ContractTemplateId { get; set; } // ContractTemplateID (length: 50)
        public string BudgetSubTypeId { get; set; } // BudgetSubTypeID (length: 50)
        public string F1 { get; set; } // F1 (length: 1000)
        public string F2 { get; set; } // F2 (length: 1000)
        public string F3 { get; set; } // F3 (length: 1000)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Foreign keys

        /// <summary>
        /// Parent TbBudgetSubType pointed by [TB_Template_Budget_Relate].([BudgetSubTypeId]) (RefTB_BudgetSubType155)
        /// </summary>
        public virtual TbBudgetSubType TbBudgetSubType { get; set; } // RefTB_BudgetSubType155

        /// <summary>
        /// Parent TbContractTemplate pointed by [TB_Template_Budget_Relate].([ContractTemplateId]) (RefTB_Contract_Template153)
        /// </summary>
        public virtual TbContractTemplate TbContractTemplate { get; set; } // RefTB_Contract_Template153
    }

}
// </auto-generated>
