// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbUser : Entity<Guid>
    {
        public string UserId { get; set; } // UserID (Primary key) (length: 50)
        public string UserLoginId { get; set; } // UserLoginID (length: 50)
        public string Password { get; set; } // Password (length: 50)
        public string UserCode { get; set; } // UserCode (length: 50)
        public string UserName { get; set; } // UserName (length: 50)
        public string UserType { get; set; } // UserType (length: 1)
        public string Email { get; set; } // Email (length: 200)
        public string MobilePhone { get; set; } // MobilePhone (length: 150)
        public string BusinessTelephone { get; set; } // BusinessTelephone (length: 50)
        public System.DateTime? BirthDay { get; set; } // BirthDay
        public string Gender { get; set; } // Gender (length: 50)
        public string Nationality { get; set; } // Nationality (length: 50)
        public string NativePlace { get; set; } // NativePlace (length: 50)
        public string PaperType { get; set; } // PaperType (length: 50)
        public string PaperNumber { get; set; } // PaperNumber (length: 50)
        public System.DateTime? JoinDate { get; set; } // JoinDate
        public System.DateTime? LeaveDate { get; set; } // LeaveDate
        public string Education { get; set; } // Education (length: 50)
        public string MaritalStatus { get; set; } // MaritalStatus (length: 50)
        public string Bank { get; set; } // Bank (length: 50)
        public string BankAccount { get; set; } // BankAccount (length: 50)
        public int? Status { get; set; } // Status
        public string Creator { get; set; } // Creator (length: 50)
        public System.DateTime? CreateDate { get; set; } // CreateDate
        public string UpdateUser { get; set; } // UpdateUser (length: 50)
        public System.DateTime? UpdateDate { get; set; } // UpdateDate
        public string EasUserCode { get; set; } // Eas_UserCode (length: 50)
        public string EasUserName { get; set; } // Eas_UserName (length: 50)
        public string JobOrder { get; set; } // JobOrder (length: 100)
        public string BusinessLeader { get; set; } // BusinessLeader (length: 50)
        public System.DateTime? BeginWorkDate { get; set; } // BeginWorkDate
        public string PositionTemp { get; set; } // Position_Temp (length: 50)
        public string RankId { get; set; } // RankID (length: 50)
        public string RankCode { get; set; } // RankCode (length: 50)
        public string RankName { get; set; } // RankName (length: 50)
        public decimal? ReimbursementAmount { get; set; } // ReimbursementAmount

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }




        // Reverse navigation

        /// <summary>
        /// Child SysUserRoles where [SYS_UserRole].[UserID] point to this entity (RefTB_User10)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysUserRole> SysUserRoles { get; set; } // SYS_UserRole.RefTB_User10
        /// <summary>
        /// Child TbOrgUserRelates where [TB_Org_User_Relate].[UserID] point to this entity (RefTB_User5)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<TbOrgUserRelate> TbOrgUserRelates { get; set; } // TB_Org_User_Relate.RefTB_User5

        public TbUser()
        {
            SysUserRoles = new System.Collections.Generic.List<SysUserRole>();
            TbOrgUserRelates = new System.Collections.Generic.List<TbOrgUserRelate>();
        }
    }

}
// </auto-generated>
