// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // TB_WeekdaysAndHolidays
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TbWeekdaysAndHoliday : Entity<Guid>
    {
        public string DaysId { get; set; } // DaysID (Primary key) (length: 50)
        public string WhName { get; set; } // WHName (length: 50)
        public System.DateTime? Dates { get; set; } // Dates
        public string DayType { get; set; } // DayType (length: 10)
        public string Remark { get; set; } // Remark (length: 1000)
        public string F1 { get; set; } // F1 (length: 100)
        public string F2 { get; set; } // F2 (length: 100)
        public string F3 { get; set; } // F3 (length: 100)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
