// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'temp_t4_t7_budgettype_0725' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // temp_t4_t7_budgettype_0725
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TempT4T7Budgettype0725 : Entity<Guid>
    {
        public string 项目 { get; set; } // 项目 (length: 255)
        public string 地块65288大地块65289 { get; set; } // 地块（大地块） (length: 255)
        public string 行政部门65288行政t465289 { get; set; } // 行政部门（行政T4） (length: 255)
        public string 费用类别 { get; set; } // 费用类别 (length: 255)
        public string 预算t4 { get; set; } // 预算T4 (length: 255)
        public string 预算t765288小地块65289 { get; set; } // 预算T7（小地块） (length: 255)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
