// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table 'temp_progress_0328' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // temp_progress_0328
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TempProgress0328 : Entity<Guid>
    {
        public string 合同编码 { get; set; } // 合同编码 (length: 255)
        public string 合同名称 { get; set; } // 合同名称 (length: 255)
        public string 供应商名称 { get; set; } // 供应商名称 (length: 255)
        public string 合同期间1 { get; set; } // 合同期间1 (length: 255)
        public string 合同期间2 { get; set; } // 合同期间2 (length: 255)
        public double? 合同总金额 { get; set; } // 合同总金额
        public double? 上月进度产值 { get; set; } // 上月进度产值
        public double? 当月进度产值 { get; set; } // 当月进度产值
        public string C3月 { get; set; } // 3月 (length: 255)
        public string C2月 { get; set; } // 2月 (length: 255)
        public string C1月 { get; set; } // 1月 (length: 255)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
