// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table '供应商开户行信息' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // 供应商开户行信息
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class 供应商开户行信息 : Entity<Guid>
    {
        public string SupplierId { get; set; } // SupplierID (length: 255)
        public string 城市 { get; set; } // 城市 (length: 255)
        public string 银行名称 { get; set; } // 银行名称 (length: 255)
        public string 付款支行 { get; set; } // 付款支行 (length: 255)
        public string 付款帐号 { get; set; } // 付款帐号 (length: 255)
        public string C40无列名41 { get; set; } // (无列名) (length: 255)
        public string ParameterId { get; set; } // ParameterID (length: 255)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
