// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table '成本报表_1' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // 成本报表_1
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class 成本报表1 : Entity<Guid>
    {
        public string 付款公司 { get; set; } // 付款公司 (length: 255)
        public string 部门编码65288T465289 { get; set; } // 部门编码（T4） (length: 255)
        public string 地块编码65288T765289 { get; set; } // 地块编码（T7） (length: 255)
        public string 预算编码65288T865289 { get; set; } // 预算编码（T8） (length: 255)
        public double? 账上金额201709 { get; set; } // 账上金额2017-09
        public double? 账上金额201710 { get; set; } // 账上金额2017-10
        public double? 账上金额201711 { get; set; } // 账上金额2017-11

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
