// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table '用户组织关系' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // 用户组织关系
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class 用户组织关系 : Entity<Guid>
    {
        public string ObjectId { get; set; } // ObjectId (length: 255)
        public string ObjectName { get; set; } // ObjectName (length: 255)
        public string PostName { get; set; } // PostName (length: 255)
        public string UserId { get; set; } // UserId (length: 255)
        public string UserName { get; set; } // UserName (length: 255)
        public string LoginName { get; set; } // LoginName (length: 255)
        public string UserNumber { get; set; } // UserNumber (length: 255)
        public string Rank { get; set; } // Rank (length: 255)
        public string Password { get; set; } // Password (length: 255)
        public string Email { get; set; } // Email (length: 255)
        public string EnableReceiveEmail { get; set; } // EnableReceiveEmail (length: 255)
        public string DefaultPost { get; set; } // DefaultPost (length: 255)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
