// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table '部门费用类别mapping' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // 部门费用类别mapping
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class 部门费用类别mapping : Entity<Guid>
    {
        public string 项目 { get; set; } // 项目 (length: 255)
        public string 地块 { get; set; } // 地块 (length: 255)
        public string 行政部门 { get; set; } // 行政部门 (length: 255)
        public string 费用类别 { get; set; } // 费用类别 (length: 255)
        public string 预算t4 { get; set; } // 预算T4 (length: 255)
        public string 预算t7 { get; set; } // 预算T7 (length: 255)
        public string 生效日期 { get; set; } // 生效日期 (length: 255)
        public string 失效日期 { get; set; } // 失效日期 (length: 255)
        public string Id { get; set; } // id (length: 50)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
