// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EMS.Entities
{
    using Abp.Domain.Entities;
    using System;

    // The table '预算T7和实际T7的mapping' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // 预算T7和实际T7的mapping
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class 预算t7和实际t7的mapping : Entity<Guid>
    {
        public string 项目 { get; set; } // 项目 (length: 255)
        public string 预算地块 { get; set; } // 预算地块 (length: 255)
        public string 预算t7 { get; set; } // 预算T7 (length: 255)
        public string SunDb { get; set; } // SUN_DB (length: 255)
        public string EpasEntity { get; set; } // EPAS Entity (length: 255)
        public string 付款公司 { get; set; } // 付款公司 (length: 255)
        public string 开始日期 { get; set; } // 开始日期 (length: 255)
        public string 结束日期 { get; set; } // 结束日期 (length: 255)
        public string F9 { get; set; } // F9 (length: 255)

 //public DateTime CreationTime { get; set; }
 //public DateTime CreatorUserId { get; set; }
 //public DateTime LastModificationTime { get; set; }
 //public DateTime LastModifierUserId { get; set; }
 //public DateTime IsDeleted { get; set; }
 //public DateTime DeletionTime { get; set; }
 //public DateTime DeleterUserId { get; set; }



    }

}
// </auto-generated>
